/* =========================================================
   NGÂN HÀNG CÂU HỎI — LỊCH SỬ 12 (KẾT NỐI TRI THỨC) — TẬP 1
   Đợt 1: Bài 1 (40 câu) + Bài 2 (40 câu)
   ========================================================= */

const QUIZ_TOPICS = [
  { id: "bai1",  name: "Bài 1 — Liên hợp quốc",                              code: "Bài 1" },
  { id: "bai2",  name: "Bài 2 — Trật tự thế giới trong Chiến tranh lạnh",    code: "Bài 2" },
  { id: "bai3",  name: "Bài 3 — Trật tự thế giới sau Chiến tranh lạnh",      code: "Bài 3" },
  { id: "bai4",  name: "Bài 4 — Sự ra đời và phát triển của ASEAN",          code: "Bài 4" },
  { id: "bai5",  name: "Bài 5 — Cộng đồng ASEAN",                            code: "Bài 5" },
  { id: "bai6",  name: "Bài 6 — Cách mạng tháng Tám năm 1945",               code: "Bài 6" },
  { id: "bai7",  name: "Bài 7 — Kháng chiến chống Pháp (1945–1954)",         code: "Bài 7" },
  { id: "bai8",  name: "Bài 8 — Kháng chiến chống Mỹ (1954–1975)",           code: "Bài 8" },
  { id: "bai9",  name: "Bài 9 — Việt Nam sau năm 1975",                      code: "Bài 9" },
  { id: "bai10", name: "Bài 10 — Công cuộc Đổi mới từ năm 1986",             code: "Bài 10" },
  { id: "bai11", name: "Bài 11 — Việt Nam hội nhập quốc tế",                 code: "Bài 11" },
  { id: "bai12", name: "Bài 12 — Lịch sử địa phương",                        code: "Bài 12" },
];

const QUIZ_QUESTIONS = [

  /* ================= BÀI 1: LIÊN HỢP QUỐC (40 câu) ================= */
  { id:"b1-01", topic:"bai1", q:"Hội nghị quốc tế nào đã thông qua bản Hiến chương Liên hợp quốc?", options:["Hội nghị Ianta","Hội nghị San Francisco","Hội nghị Pốt-xđam","Hội nghị Bàn Môn Điếm"], answer:1 },
  { id:"b1-02", topic:"bai1", q:"Hội nghị San Francisco diễn ra trong khoảng thời gian nào?", options:["4/2 – 11/2/1945","25/4 – 26/6/1945","17/7 – 2/8/1945","14/8 – 2/9/1945"], answer:1 },
  { id:"b1-03", topic:"bai1", q:"Hiến chương Liên hợp quốc chính thức có hiệu lực vào ngày tháng năm nào?", options:["26/6/1945","24/10/1945","25/4/1945","20/9/1977"], answer:1 },
  { id:"b1-04", topic:"bai1", q:"Có bao nhiêu quốc gia tham gia sáng lập tổ chức Liên hợp quốc?", options:["50 nước","51 nước","5 nước","15 nước"], answer:1 },
  { id:"b1-05", topic:"bai1", q:"Trụ sở chính của Liên hợp quốc đặt tại đâu?", options:["Genève, Thụy Sĩ","Bruxelles, Bỉ","New York, Mỹ","Paris, Pháp"], answer:2 },
  { id:"b1-06", topic:"bai1", q:"Mục tiêu hàng đầu của Liên hợp quốc được nêu trong Hiến chương là gì?", options:["Phát triển kinh tế toàn cầu","Duy trì hòa bình và an ninh thế giới","Bảo vệ môi trường","Thúc đẩy thương mại tự do"], answer:1 },
  { id:"b1-07", topic:"bai1", q:"Cơ quan nào của Liên hợp quốc giữ vai trò trọng yếu trong việc duy trì hòa bình, an ninh thế giới?", options:["Đại hội đồng","Hội đồng Bảo an","Ban Thư ký","Hội đồng Kinh tế và Xã hội"], answer:1 },
  { id:"b1-08", topic:"bai1", q:"Hội đồng Bảo an Liên hợp quốc có bao nhiêu ủy viên thường trực?", options:["3","4","5","6"], answer:2 },
  { id:"b1-09", topic:"bai1", q:"Quốc gia nào sau đây KHÔNG phải là ủy viên thường trực của Hội đồng Bảo an?", options:["Mỹ","Anh","Đức","Pháp"], answer:2 },
  { id:"b1-10", topic:"bai1", q:"Năm ủy viên thường trực Hội đồng Bảo an Liên hợp quốc gồm những nước nào?", options:["Mỹ, Anh, Pháp, Nga, Trung Quốc","Mỹ, Anh, Pháp, Đức, Nhật","Mỹ, Nga, Ấn Độ, Trung Quốc, Anh","Mỹ, Anh, Pháp, Đức, Nga"], answer:0 },
  { id:"b1-11", topic:"bai1", q:"Nguyên tắc nào cho phép 5 ủy viên thường trực Hội đồng Bảo an có quyền phủ quyết?", options:["Bình đẳng chủ quyền","Nhất trí giữa 5 ủy viên thường trực","Không can thiệp nội bộ","Giải quyết tranh chấp bằng biện pháp hòa bình"], answer:1 },
  { id:"b1-12", topic:"bai1", q:"Cơ quan nào của Liên hợp quốc gồm đại diện của tất cả các quốc gia thành viên, mỗi nước một phiếu?", options:["Hội đồng Bảo an","Đại hội đồng","Ban Thư ký","Tòa án Công lý Quốc tế"], answer:1 },
  { id:"b1-13", topic:"bai1", q:"Người đứng đầu Ban Thư ký Liên hợp quốc được gọi là gì?", options:["Chủ tịch","Tổng thư ký","Tổng giám đốc","Chủ tịch Hội đồng"], answer:1 },
  { id:"b1-14", topic:"bai1", q:"Cơ quan tư pháp chính của Liên hợp quốc là cơ quan nào?", options:["Tòa án Công lý Quốc tế","Hội đồng Bảo an","Ban Thư ký","Hội đồng Quản thác"], answer:0 },
  { id:"b1-15", topic:"bai1", q:"Trong hệ thống Liên hợp quốc, cơ quan nào phụ trách hợp tác quốc tế về kinh tế, văn hóa, xã hội, giáo dục, y tế?", options:["Hội đồng Bảo an","Hội đồng Kinh tế và Xã hội","Ban Thư ký","Hội đồng Quản thác"], answer:1 },
  { id:"b1-16", topic:"bai1", q:"Liên hợp quốc ra đời nhằm thay thế cho tổ chức quốc tế nào được thành lập trước Chiến tranh thế giới thứ hai?", options:["Hội Quốc liên","Khối Thịnh vượng chung","Liên minh châu Âu","Phong trào Không liên kết"], answer:0 },
  { id:"b1-17", topic:"bai1", q:"Nguyên tắc nào sau đây KHÔNG phải là nguyên tắc hoạt động của Liên hợp quốc?", options:["Bình đẳng chủ quyền giữa các quốc gia","Không can thiệp vào công việc nội bộ của các nước","Giải quyết tranh chấp quốc tế bằng biện pháp hòa bình","Ưu tiên lợi ích của các nước lớn"], answer:3 },
  { id:"b1-18", topic:"bai1", q:"Việt Nam chính thức gia nhập Liên hợp quốc vào thời gian nào?", options:["20/9/1977","28/7/1995","25/6/1950","2/9/1945"], answer:0 },
  { id:"b1-19", topic:"bai1", q:"Việt Nam là thành viên thứ bao nhiêu của Liên hợp quốc?", options:["129","149","159","195"], answer:1 },
  { id:"b1-20", topic:"bai1", q:"Việc Việt Nam gia nhập Liên hợp quốc năm 1977 có ý nghĩa như thế nào?", options:["Khẳng định vị thế, tạo điều kiện tranh thủ sự ủng hộ và hợp tác quốc tế","Chấm dứt hoàn toàn chiến tranh ở Việt Nam","Giúp Việt Nam gia nhập ASEAN ngay lập tức","Xóa bỏ ngay lệnh cấm vận của Mỹ"], answer:0 },
  { id:"b1-21", topic:"bai1", q:"Việt Nam đã trúng cử Ủy viên không thường trực Hội đồng Bảo an Liên hợp quốc vào các nhiệm kỳ nào?", options:["2008–2009 và 2020–2021","1995–1996 và 2005–2006","1977–1978 và 1987–1988","2015–2016 và 2018–2019"], answer:0 },
  { id:"b1-22", topic:"bai1", q:"Liên hợp quốc được thành lập nhằm mục đích chính nào sau đây?", options:["Duy trì hòa bình và an ninh thế giới, phát triển quan hệ hữu nghị giữa các dân tộc","Thành lập một liên minh quân sự chống phát xít","Chia lại thế giới giữa các cường quốc","Thúc đẩy chủ nghĩa thực dân mới"], answer:0 },
  { id:"b1-23", topic:"bai1", q:"Cơ quan nào của Liên hợp quốc có thẩm quyền quyết định các biện pháp trừng phạt, can thiệp quân sự khi hòa bình bị đe dọa?", options:["Đại hội đồng","Hội đồng Bảo an","Hội đồng Kinh tế và Xã hội","Tòa án Công lý Quốc tế"], answer:1 },
  { id:"b1-24", topic:"bai1", q:"Việt Nam đã tham gia lực lượng gìn giữ hòa bình Liên hợp quốc từ năm nào?", options:["2014","2000","1995","2020"], answer:0 },
  { id:"b1-25", topic:"bai1", q:"Đâu KHÔNG phải là cơ quan chính của Liên hợp quốc theo Hiến chương?", options:["Đại hội đồng","Hội đồng Bảo an","Hội đồng Kinh tế và Xã hội","ASEAN"], answer:3 },
  { id:"b1-26", topic:"bai1", q:"Số lượng thành viên Liên hợp quốc hiện nay (2024) là bao nhiêu?", options:["193","195","200","150"], answer:0 },
  { id:"b1-27", topic:"bai1", q:"Liên hợp quốc có bao nhiêu ngôn ngữ chính thức?", options:["5","6","7","8"], answer:1 },
  { id:"b1-28", topic:"bai1", q:"Một trong những thành tựu lớn nhất của Liên hợp quốc trong hơn 70 năm qua là gì?", options:["Ngăn chặn được Chiến tranh thế giới thứ ba, thúc đẩy hợp tác phát triển","Xóa bỏ hoàn toàn đói nghèo trên thế giới","Chấm dứt mọi cuộc xung đột vũ trang","Thành lập chính phủ thế giới"], answer:0 },
  { id:"b1-29", topic:"bai1", q:"Việt Nam đảm nhận vai trò Chủ tịch Hội đồng Bảo an Liên hợp quốc vào tháng nào năm 2020?", options:["1/2020","4/2020","7/2020","10/2020"], answer:0 },
  { id:"b1-30", topic:"bai1", q:"Theo Hiến chương, Liên hợp quốc hoạt động dựa trên nguyên tắc cơ bản nào?", options:["Bình đẳng chủ quyền của tất cả các quốc gia thành viên","Ưu tiên các nước lớn","Can thiệp vào nội bộ các nước","Sử dụng vũ lực để giải quyết tranh chấp"], answer:0 },
  { id:"b1-31", topic:"bai1", q:"Hội nghị Ianta (2/1945) có liên quan gì đến sự ra đời của Liên hợp quốc?", options:["Đã thỏa thuận thành lập Liên hợp quốc sau chiến tranh","Đã bầu Tổng thư ký đầu tiên","Đã thông qua Hiến chương Liên hợp quốc","Đã quyết định trụ sở Liên hợp quốc"], answer:0 },
  { id:"b1-32", topic:"bai1", q:"Tổ chức nào sau đây là cơ quan chuyên môn của Liên hợp quốc?", options:["UNESCO","ASEAN","NATO","EU"], answer:0 },
  { id:"b1-33", topic:"bai1", q:"UNICEF là quỹ của Liên hợp quốc hoạt động trong lĩnh vực nào?", options:["Nhi đồng","Nông nghiệp","Y tế","Giáo dục"], answer:0 },
  { id:"b1-34", topic:"bai1", q:"WHO là tổ chức của Liên hợp quốc hoạt động trong lĩnh vực nào?", options:["Y tế","Văn hóa","Giáo dục","Lao động"], answer:0 },
  { id:"b1-35", topic:"bai1", q:"IMF là tổ chức quốc tế có quan hệ với Liên hợp quốc hoạt động trong lĩnh vực nào?", options:["Tiền tệ quốc tế","Nông nghiệp","Giáo dục","Y tế"], answer:0 },
  { id:"b1-36", topic:"bai1", q:"Đâu là hạn chế lớn nhất của Liên hợp quốc hiện nay?", options:["Chưa giải quyết triệt để các xung đột, đói nghèo, dịch bệnh toàn cầu","Không có đủ thành viên","Không có trụ sở","Không có Hiến chương"], answer:0 },
  { id:"b1-37", topic:"bai1", q:"Cơ quan nào của Liên hợp quốc có vai trò giám sát, thúc đẩy nhân quyền trên toàn thế giới?", options:["Hội đồng Nhân quyền","Hội đồng Bảo an","Đại hội đồng","Ban Thư ký"], answer:0 },
  { id:"b1-38", topic:"bai1", q:"Việt Nam tham gia Liên hợp quốc góp phần quan trọng vào việc gì?", options:["Nâng cao vị thế quốc gia và thúc đẩy hòa bình, hợp tác khu vực, quốc tế","Xóa bỏ mọi khó khăn kinh tế trong nước","Thay thế ASEAN","Chống lại các nước lớn"], answer:0 },
  { id:"b1-39", topic:"bai1", q:"Việt Nam đã được bầu làm Ủy viên không thường trực Hội đồng Bảo an nhiệm kỳ 2020–2021 với số phiếu bao nhiêu?", options:["192/193","180/193","150/193","193/193"], answer:0 },
  { id:"b1-40", topic:"bai1", q:"Sự kiện Việt Nam gia nhập Liên hợp quốc (1977) diễn ra trong bối cảnh nào?", options:["Đất nước vừa thống nhất, còn nhiều khó khăn, bị bao vây cấm vận","Đang kháng chiến chống Mỹ","Vừa giành độc lập từ Pháp","Đang tiến hành Đổi mới"], answer:0 },

  /* ================= BÀI 2: TRẬT TỰ THẾ GIỚI TRONG CHIẾN TRANH LẠNH (40 câu) ================= */
  { id:"b2-01", topic:"bai2", q:"Hội nghị Ianta (Yalta) diễn ra vào thời gian nào?", options:["4/2 – 11/2/1945","17/7 – 2/8/1945","25/4 – 26/6/1945","14/8/1945"], answer:0 },
  { id:"b2-02", topic:"bai2", q:"Hội nghị Ianta có sự tham gia của nguyên thủ ba cường quốc nào?", options:["Mỹ, Anh, Pháp","Mỹ, Anh, Liên Xô","Mỹ, Liên Xô, Trung Quốc","Anh, Pháp, Liên Xô"], answer:1 },
  { id:"b2-03", topic:"bai2", q:"Ai là người đại diện cho Liên Xô tại Hội nghị Ianta?", options:["Lenin","Khrushchev","Stalin","Gorbachev"], answer:2 },
  { id:"b2-04", topic:"bai2", q:"Ai đại diện cho Mỹ tại Hội nghị Ianta?", options:["Roosevelt","Truman","Eisenhower","Kennedy"], answer:0 },
  { id:"b2-05", topic:"bai2", q:"Ai đại diện cho Anh tại Hội nghị Ianta?", options:["Churchill","Attlee","Thatcher","Blair"], answer:0 },
  { id:"b2-06", topic:"bai2", q:"“Trật tự hai cực Ianta” là trật tự thế giới do các cường quốc nào chi phối?", options:["Mỹ và Liên Xô","Mỹ và Trung Quốc","Anh và Pháp","Liên Xô và Trung Quốc"], answer:0 },
  { id:"b2-07", topic:"bai2", q:"Theo thỏa thuận tại Hội nghị Ianta, châu Âu bị phân chia thành mấy phạm vi ảnh hưởng chính?", options:["2 (Đông Âu – Liên Xô, Tây Âu – Mỹ/Anh/Pháp)","3","4","5"], answer:0 },
  { id:"b2-08", topic:"bai2", q:"Theo thỏa thuận tại Hội nghị Ianta, nước Đức bị chia thành bao nhiêu khu vực chiếm đóng?", options:["2","3","4","5"], answer:2 },
  { id:"b2-09", topic:"bai2", q:"Theo Hội nghị Ianta, quân đội Liên Xô sẽ chiếm đóng vùng nào của nước Đức?", options:["Đông Đức","Tây Đức","Nam Đức","Bắc Đức"], answer:0 },
  { id:"b2-10", topic:"bai2", q:"Hội nghị Ianta đã thỏa thuận việc Liên Xô tham chiến chống Nhật trong vòng bao lâu sau khi Đức đầu hàng?", options:["1 tháng","2 tháng","3 tháng","6 tháng"], answer:2 },
  { id:"b2-11", topic:"bai2", q:"Chiến tranh lạnh chính thức bắt đầu bằng sự kiện nào?", options:["Học thuyết Truman (3/1947)","NATO thành lập (1949)","Khối Vác-sa-va thành lập (1955)","Bức tường Berlin dựng lên (1961)"], answer:0 },
  { id:"b2-12", topic:"bai2", q:"Học thuyết Truman (1947) đánh dấu sự khởi đầu của sự kiện lịch sử nào?", options:["Chiến tranh lạnh giữa Mỹ và Liên Xô","Chiến tranh thế giới thứ ba","Sự hình thành ASEAN","Phong trào Không liên kết"], answer:0 },
  { id:"b2-13", topic:"bai2", q:"“Kế hoạch Marshall” (1947) được Mỹ đề ra nhằm mục đích gì?", options:["Viện trợ kinh tế phục hưng Tây Âu, qua đó lôi kéo đồng minh chống Liên Xô","Viện trợ quân sự cho Nhật Bản","Xây dựng trụ sở Liên hợp quốc","Hỗ trợ thành lập ASEAN"], answer:0 },
  { id:"b2-14", topic:"bai2", q:"Khối quân sự NATO do Mỹ đứng đầu được thành lập vào năm nào?", options:["1947","1949","1955","1957"], answer:1 },
  { id:"b2-15", topic:"bai2", q:"Tổ chức Hiệp ước Vác-sa-va do Liên Xô đứng đầu được thành lập vào năm nào?", options:["1949","1950","1955","1961"], answer:2 },
  { id:"b2-16", topic:"bai2", q:"NATO là viết tắt của tổ chức nào?", options:["Tổ chức Hiệp ước Bắc Đại Tây Dương","Tổ chức Hiệp ước Đông Nam Á","Tổ chức Hiệp ước Trung Đông","Tổ chức Hiệp ước Vác-sa-va"], answer:0 },
  { id:"b2-17", topic:"bai2", q:"SEATO là tổ chức quân sự do Mỹ lập ra nhằm mục đích gì?", options:["Chống phong trào giải phóng dân tộc ở Đông Nam Á","Bảo vệ hòa bình Đông Nam Á","Hỗ trợ ASEAN phát triển","Chống chủ nghĩa thực dân cũ"], answer:0 },
  { id:"b2-18", topic:"bai2", q:"Sự kiện nào đánh dấu sự chia cắt nước Đức trong Chiến tranh lạnh?", options:["Bức tường Berlin được dựng lên năm 1961","Hiệp định Potsdam 1945","NATO thành lập 1949","Khối Vác-sa-va thành lập 1955"], answer:0 },
  { id:"b2-19", topic:"bai2", q:"Bức tường Berlin được dựng lên vào năm nào?", options:["1949","1955","1961","1971"], answer:2 },
  { id:"b2-20", topic:"bai2", q:"Cục diện đối đầu Đông – Tây trong Chiến tranh lạnh được phản ánh rõ nét qua cuộc chiến tranh nào ở châu Á?", options:["Chiến tranh Triều Tiên (1950–1953)","Cách mạng Tân Hợi","Chiến tranh Nha phiến","Khởi nghĩa Yên Bái"], answer:0 },
  { id:"b2-21", topic:"bai2", q:"Chiến tranh Triều Tiên kết thúc bằng hiệp định nào và năm nào?", options:["Hiệp định đình chiến Panmunjom (1953)","Hiệp định Genève (1954)","Hiệp định Pari (1973)","Hiệp định Portsmouth (1905)"], answer:0 },
  { id:"b2-22", topic:"bai2", q:"Cuộc khủng hoảng tên lửa Cuba (1962) diễn ra giữa hai nhà lãnh đạo nào?", options:["Kennedy và Khrushchev","Eisenhower và Stalin","Reagan và Gorbachev","Nixon và Brezhnev"], answer:0 },
  { id:"b2-23", topic:"bai2", q:"Cuộc khủng hoảng tên lửa Cuba (1962) đưa thế giới đến bờ vực của sự kiện gì?", options:["Chiến tranh hạt nhân","Chiến tranh thương mại","Khủng hoảng dầu mỏ","Sụp đổ chủ nghĩa xã hội"], answer:0 },
  { id:"b2-24", topic:"bai2", q:"Trong Chiến tranh lạnh, Mỹ và Liên Xô chủ yếu đối đầu bằng phương thức nào?", options:["Chạy đua vũ trang, chiến tranh cục bộ, chiến tranh kinh tế, tuyên truyền","Đối đầu trực tiếp bằng quân đội","Chiến tranh hạt nhân toàn diện","Không đối đầu gì"], answer:0 },
  { id:"b2-25", topic:"bai2", q:"“Chiến tranh lạnh” là gì?", options:["Chính sách thù địch, căng thẳng giữa Mỹ và Liên Xô và các đồng minh, không dùng vũ lực trực tiếp","Một cuộc chiến tranh quân sự trực tiếp","Một cuộc chiến tranh kinh tế giữa các nước tư bản","Một cuộc chiến tranh ở vùng cực"], answer:0 },
  { id:"b2-26", topic:"bai2", q:"Đặc trưng nổi bật của trật tự hai cực Ianta là gì?", options:["Thế giới chia thành hai phe do Mỹ và Liên Xô đứng đầu, đối đầu nhau","Thế giới đa cực","Thế giới đơn cực do Mỹ lãnh đạo","Thế giới không có cường quốc nào"], answer:0 },
  { id:"b2-27", topic:"bai2", q:"Tổ chức Hiệp ước Vác-sa-va được thành lập nhằm mục đích gì?", options:["Đối phó với việc NATO kết nạp Tây Đức","Chống lại Liên hợp quốc","Xâm lược các nước Đông Âu","Ủng hộ chủ nghĩa thực dân"], answer:0 },
  { id:"b2-28", topic:"bai2", q:"Sau Chiến tranh thế giới thứ hai, hai siêu cường nào đứng đầu hai phe đối lập?", options:["Mỹ và Liên Xô","Anh và Pháp","Đức và Nhật","Trung Quốc và Ấn Độ"], answer:0 },
  { id:"b2-29", topic:"bai2", q:"Nguyên nhân chính dẫn đến Chiến tranh lạnh là gì?", options:["Sự đối lập về mục tiêu và chiến lược giữa Mỹ và Liên Xô","Mâu thuẫn về thuộc địa","Chiến tranh thương mại","Sự suy yếu của châu Âu"], answer:0 },
  { id:"b2-30", topic:"bai2", q:"Hệ quả lớn nhất của Chiến tranh lạnh đối với thế giới là gì?", options:["Thế giới luôn trong tình trạng căng thẳng, chạy đua vũ trang, nguy cơ chiến tranh hạt nhân","Thế giới hòa bình hoàn toàn","Chủ nghĩa thực dân phục hồi","Liên hợp quốc giải thể"], answer:0 },
  { id:"b2-31", topic:"bai2", q:"Trong Chiến tranh lạnh, Việt Nam bị ảnh hưởng bởi cục diện nào?", options:["Bị chia cắt thành hai miền theo vĩ tuyến 17, chịu tác động của hai phe","Được hưởng hòa bình ngay từ 1954","Không bị ảnh hưởng gì","Trở thành đồng minh của NATO"], answer:0 },
  { id:"b2-32", topic:"bai2", q:"Hiệp định Genève (1954) về Đông Dương được ký kết trong bối cảnh nào của Chiến tranh lạnh?", options:["Chiến tranh lạnh đang diễn ra căng thẳng, các nước lớn can thiệp vào Đông Dương","Chiến tranh lạnh đã kết thúc","Mỹ và Liên Xô đang hợp tác","NATO đã giải thể"], answer:0 },
  { id:"b2-33", topic:"bai2", q:"Mỹ can thiệp vào Việt Nam sau 1954 nhằm mục đích gì trong bối cảnh Chiến tranh lạnh?", options:["Ngăn chặn ảnh hưởng của chủ nghĩa cộng sản lan rộng ở Đông Nam Á","Giúp Việt Nam phát triển kinh tế","Ủng hộ Việt Nam thống nhất","Bảo vệ chủ quyền Việt Nam"], answer:0 },
  { id:"b2-34", topic:"bai2", q:"“Chiến lược toàn cầu” của Mỹ trong Chiến tranh lạnh nhằm mục tiêu gì?", options:["Ngăn chặn, đẩy lùi chủ nghĩa cộng sản trên toàn thế giới","Giúp các nước nghèo phát triển","Xóa bỏ chủ nghĩa thực dân","Ủng hộ Liên Xô"], answer:0 },
  { id:"b2-35", topic:"bai2", q:"Khối SEATO (1954) gồm những nước nào tham gia sáng lập?", options:["Mỹ, Anh, Pháp, Australia, New Zealand, Pakistan, Philippines, Thái Lan","Mỹ, Liên Xô, Trung Quốc","Việt Nam, Lào, Campuchia","Ấn Độ, Nhật Bản, Hàn Quốc"], answer:0 },
  { id:"b2-36", topic:"bai2", q:"Tổ chức CENTO (1955) là liên minh quân sự do Mỹ lập ra ở khu vực nào?", options:["Trung Đông","Đông Nam Á","Bắc Âu","Nam Mỹ"], answer:0 },
  { id:"b2-37", topic:"bai2", q:"Tại sao Chiến tranh lạnh không bùng nổ thành chiến tranh thế giới thứ ba?", options:["Do tương quan lực lượng, đặc biệt là vũ khí hạt nhân, khiến cả hai bên kiềm chế","Do Liên hợp quốc cấm chiến tranh","Do nhân dân thế giới phản đối","Do kinh tế suy thoái"], answer:0 },
  { id:"b2-38", topic:"bai2", q:"Sự kiện nào đánh dấu sự sụp đổ của trật tự hai cực Ianta?", options:["Liên Xô tan rã năm 1991","Bức tường Berlin sụp đổ năm 1989","Khối Vác-sa-va giải thể năm 1991","Cả 3 sự kiện trên"], answer:3 },
  { id:"b2-39", topic:"bai2", q:"Sau khi Chiến tranh lạnh kết thúc, trật tự thế giới mới đang hình thành theo xu hướng nào?", options:["Đa cực, nhiều trung tâm","Đơn cực do Mỹ chi phối","Quay lại hai cực","Không có trật tự nào"], answer:0 },
  { id:"b2-40", topic:"bai2", q:"Bài học lớn nhất cho Việt Nam từ cục diện Chiến tranh lạnh là gì?", options:["Giữ vững độc lập, tự chủ, không bị lôi kéo vào đối đầu giữa các cường quốc","Dựa hoàn toàn vào một cường quốc","Chạy đua vũ trang","Đóng cửa với thế giới"], answer:0 },

];