/* =========================================================
   NGÂN HÀNG CÂU HỎI — LỊCH SỬ 12 (KẾT NỐI TRI THỨC) — TẬP 1
   12 bài × 20 câu = 240 câu
   ========================================================= */

const QUIZ_TOPICS = [
  { id: "bai1",  name: "Bài 1 — Liên hợp quốc",                              code: "Bài 1" },
  { id: "bai2",  name: "Bài 2 — Trật tự thế giới trong Chiến tranh lạnh",    code: "Bài 2" },
  { id: "bai3",  name: "Bài 3 — Trật tự thế giới sau Chiến tranh lạnh",      code: "Bài 3" },
  { id: "bai4",  name: "Bài 4 — Sự ra đời và phát triển của ASEAN",          code: "Bài 4" },
  { id: "bai5",  name: "Bài 5 — Cộng đồng ASEAN",                            code: "Bài 5" },
  { id: "bai6",  name: "Bài 6 — Cách mạng tháng Tám năm 1945",               code: "Bài 6" },
  { id: "bai7",  name: "Bài 7 — Kháng chiến chống Pháp (1945–1954)",         code: "Bài 7" },
  { id: "bai8",  name: "Bài 8 — Kháng chiến chống Mỹ (1954–1975)",           code: "Bài 8" },
  { id: "bai9",  name: "Bài 9 — Việt Nam sau năm 1975",                      code: "Bài 9" },
  { id: "bai10", name: "Bài 10 — Công cuộc Đổi mới từ năm 1986",             code: "Bài 10" },
  { id: "bai11", name: "Bài 11 — Việt Nam hội nhập quốc tế",                 code: "Bài 11" },
  { id: "bai12", name: "Bài 12 — Lịch sử địa phương",                        code: "Bài 12" },
];

const QUIZ_QUESTIONS = [

  /* ============ BÀI 1: LIÊN HỢP QUỐC (20 câu) ============ */
  { id:"b1-01", topic:"bai1", q:"Hội nghị quốc tế nào đã thông qua bản Hiến chương Liên hợp quốc?", options:["Hội nghị Ianta","Hội nghị San Francisco","Hội nghị Pốt-xđam","Hội nghị Bàn Môn Điếm"], answer:1 },
  { id:"b1-02", topic:"bai1", q:"Hiến chương Liên hợp quốc chính thức có hiệu lực vào ngày tháng năm nào?", options:["26/6/1945","24/10/1945","25/4/1945","20/9/1977"], answer:1 },
  { id:"b1-03", topic:"bai1", q:"Hội nghị San Francisco diễn ra trong khoảng thời gian nào?", options:["4/2 – 11/2/1945","25/4 – 26/6/1945","17/7 – 2/8/1945","14/8 – 2/9/1945"], answer:1 },
  { id:"b1-04", topic:"bai1", q:"Có bao nhiêu quốc gia tham gia sáng lập tổ chức Liên hợp quốc?", options:["50 nước","51 nước","5 nước","15 nước"], answer:1 },
  { id:"b1-05", topic:"bai1", q:"Trụ sở chính của Liên hợp quốc đặt tại đâu?", options:["Genève, Thụy Sĩ","Bruxelles, Bỉ","New York, Mỹ","Paris, Pháp"], answer:2 },
  { id:"b1-06", topic:"bai1", q:"Mục tiêu hàng đầu của Liên hợp quốc được nêu trong Hiến chương là gì?", options:["Phát triển kinh tế toàn cầu","Duy trì hòa bình và an ninh thế giới","Bảo vệ môi trường","Thúc đẩy thương mại tự do"], answer:1 },
  { id:"b1-07", topic:"bai1", q:"Cơ quan nào của Liên hợp quốc giữ vai trò trọng yếu trong việc duy trì hòa bình, an ninh thế giới?", options:["Đại hội đồng","Hội đồng Bảo an","Ban Thư ký","Hội đồng Kinh tế và Xã hội"], answer:1 },
  { id:"b1-08", topic:"bai1", q:"Hội đồng Bảo an Liên hợp quốc có bao nhiêu ủy viên thường trực?", options:["3","4","5","6"], answer:2 },
  { id:"b1-09", topic:"bai1", q:"Quốc gia nào sau đây KHÔNG phải là ủy viên thường trực của Hội đồng Bảo an?", options:["Mỹ","Anh","Đức","Pháp"], answer:2 },
  { id:"b1-10", topic:"bai1", q:"Năm ủy viên thường trực Hội đồng Bảo an Liên hợp quốc gồm những nước nào?", options:["Mỹ, Anh, Pháp, Nga, Trung Quốc","Mỹ, Anh, Pháp, Đức, Nhật","Mỹ, Nga, Ấn Độ, Trung Quốc, Anh","Mỹ, Anh, Pháp, Đức, Nga"], answer:0 },
  { id:"b1-11", topic:"bai1", q:"Nguyên tắc nào cho phép 5 ủy viên thường trực Hội đồng Bảo an có quyền phủ quyết?", options:["Bình đẳng chủ quyền","Nhất trí giữa 5 ủy viên thường trực","Không can thiệp nội bộ","Giải quyết tranh chấp bằng biện pháp hòa bình"], answer:1 },
  { id:"b1-12", topic:"bai1", q:"Cơ quan nào của Liên hợp quốc gồm đại diện của tất cả các quốc gia thành viên, mỗi nước một phiếu?", options:["Hội đồng Bảo an","Đại hội đồng","Ban Thư ký","Tòa án Công lý Quốc tế"], answer:1 },
  { id:"b1-13", topic:"bai1", q:"Người đứng đầu Ban Thư ký Liên hợp quốc được gọi là gì?", options:["Chủ tịch","Tổng thư ký","Tổng giám đốc","Chủ tịch Hội đồng"], answer:1 },
  { id:"b1-14", topic:"bai1", q:"Cơ quan tư pháp chính của Liên hợp quốc là cơ quan nào?", options:["Tòa án Công lý Quốc tế","Hội đồng Bảo an","Ban Thư ký","Hội đồng Quản thác"], answer:0 },
  { id:"b1-15", topic:"bai1", q:"Liên hợp quốc ra đời nhằm thay thế cho tổ chức quốc tế nào trước Chiến tranh thế giới thứ hai?", options:["Hội Quốc liên","Khối Thịnh vượng chung","Liên minh châu Âu","Phong trào Không liên kết"], answer:0 },
  { id:"b1-16", topic:"bai1", q:"Nguyên tắc nào sau đây KHÔNG phải là nguyên tắc hoạt động của Liên hợp quốc?", options:["Bình đẳng chủ quyền giữa các quốc gia","Không can thiệp vào công việc nội bộ của các nước","Giải quyết tranh chấp quốc tế bằng biện pháp hòa bình","Ưu tiên lợi ích của các nước lớn"], answer:3 },
  { id:"b1-17", topic:"bai1", q:"Việt Nam chính thức gia nhập Liên hợp quốc vào thời gian nào?", options:["20/9/1977","28/7/1995","25/6/1950","2/9/1945"], answer:0 },
  { id:"b1-18", topic:"bai1", q:"Việt Nam là thành viên thứ bao nhiêu của Liên hợp quốc?", options:["129","149","159","195"], answer:1 },
  { id:"b1-19", topic:"bai1", q:"Việt Nam đã trúng cử Ủy viên không thường trực Hội đồng Bảo an Liên hợp quốc vào các nhiệm kỳ nào?", options:["2008–2009 và 2020–2021","1995–1996 và 2005–2006","1977–1978 và 1987–1988","2015–2016 và 2018–2019"], answer:0 },
  { id:"b1-20", topic:"bai1", q:"Việc Việt Nam gia nhập Liên hợp quốc năm 1977 có ý nghĩa như thế nào?", options:["Khẳng định vị thế, tạo điều kiện tranh thủ sự ủng hộ và hợp tác quốc tế","Chấm dứt hoàn toàn chiến tranh ở Việt Nam","Giúp Việt Nam gia nhập ASEAN ngay lập tức","Xóa bỏ ngay lệnh cấm vận của Mỹ"], answer:0 },

  /* ============ BÀI 2: TRẬT TỰ THẾ GIỚI TRONG CHIẾN TRANH LẠNH (20 câu) ============ */
  { id:"b2-01", topic:"bai2", q:"Hội nghị Ianta (Yalta) diễn ra vào thời gian nào?", options:["4/2 – 11/2/1945","17/7 – 2/8/1945","25/4 – 26/6/1945","14/8/1945"], answer:0 },
  { id:"b2-02", topic:"bai2", q:"Hội nghị Ianta có sự tham gia của nguyên thủ ba cường quốc nào?", options:["Mỹ, Anh, Pháp","Mỹ, Anh, Liên Xô","Mỹ, Liên Xô, Trung Quốc","Anh, Pháp, Liên Xô"], answer:1 },
  { id:"b2-03", topic:"bai2", q:"Ai là người đại diện cho Liên Xô tại Hội nghị Ianta?", options:["Lenin","Khrushchev","Stalin","Gorbachev"], answer:2 },
  { id:"b2-04", topic:"bai2", q:"Ai đại diện cho Mỹ tại Hội nghị Ianta?", options:["Roosevelt","Truman","Eisenhower","Kennedy"], answer:0 },
  { id:"b2-05", topic:"bai2", q:"Ai đại diện cho Anh tại Hội nghị Ianta?", options:["Churchill","Attlee","Thatcher","Blair"], answer:0 },
  { id:"b2-06", topic:"bai2", q:"“Trật tự hai cực Ianta” là trật tự thế giới do các cường quốc nào chi phối?", options:["Mỹ và Liên Xô","Mỹ và Trung Quốc","Anh và Pháp","Liên Xô và Trung Quốc"], answer:0 },
  { id:"b2-07", topic:"bai2", q:"Theo thỏa thuận tại Hội nghị Ianta, châu Âu bị phân chia thành mấy phạm vi ảnh hưởng chính?", options:["2 (Đông Âu – Liên Xô, Tây Âu – Mỹ/Anh/Pháp)","3","4","5"], answer:0 },
  { id:"b2-08", topic:"bai2", q:"Theo thỏa thuận tại Hội nghị Ianta, nước Đức bị chia thành bao nhiêu khu vực chiếm đóng?", options:["2","3","4","5"], answer:2 },
  { id:"b2-09", topic:"bai2", q:"Chiến tranh lạnh chính thức bắt đầu bằng sự kiện nào?", options:["Học thuyết Truman (3/1947)","NATO thành lập (1949)","Khối Vác-sa-va thành lập (1955)","Bức tường Berlin dựng lên (1961)"], answer:0 },
  { id:"b2-10", topic:"bai2", q:"“Kế hoạch Marshall” (1947) được Mỹ đề ra nhằm mục đích gì?", options:["Viện trợ kinh tế phục hưng Tây Âu, lôi kéo đồng minh chống Liên Xô","Viện trợ quân sự cho Nhật Bản","Xây dựng trụ sở Liên hợp quốc","Hỗ trợ thành lập ASEAN"], answer:0 },
  { id:"b2-11", topic:"bai2", q:"Khối quân sự NATO do Mỹ đứng đầu được thành lập vào năm nào?", options:["1947","1949","1955","1957"], answer:1 },
  { id:"b2-12", topic:"bai2", q:"Tổ chức Hiệp ước Vác-sa-va do Liên Xô đứng đầu được thành lập vào năm nào?", options:["1949","1950","1955","1961"], answer:2 },
  { id:"b2-13", topic:"bai2", q:"NATO là viết tắt của tổ chức nào?", options:["Tổ chức Hiệp ước Bắc Đại Tây Dương","Tổ chức Hiệp ước Đông Nam Á","Tổ chức Hiệp ước Trung Đông","Tổ chức Hiệp ước Vác-sa-va"], answer:0 },
  { id:"b2-14", topic:"bai2", q:"Sự kiện nào đánh dấu sự chia cắt nước Đức trong Chiến tranh lạnh?", options:["Bức tường Berlin được dựng lên năm 1961","Hiệp định Potsdam 1945","NATO thành lập 1949","Khối Vác-sa-va thành lập 1955"], answer:0 },
  { id:"b2-15", topic:"bai2", q:"Bức tường Berlin được dựng lên vào năm nào?", options:["1949","1955","1961","1971"], answer:2 },
  { id:"b2-16", topic:"bai2", q:"Cục diện đối đầu Đông – Tây trong Chiến tranh lạnh được phản ánh rõ nét qua cuộc chiến tranh nào ở châu Á?", options:["Chiến tranh Triều Tiên (1950–1953)","Cách mạng Tân Hợi","Chiến tranh Nha phiến","Khởi nghĩa Yên Bái"], answer:0 },
  { id:"b2-17", topic:"bai2", q:"Cuộc khủng hoảng tên lửa Cuba (1962) diễn ra giữa hai nhà lãnh đạo nào?", options:["Kennedy và Khrushchev","Eisenhower và Stalin","Reagan và Gorbachev","Nixon và Brezhnev"], answer:0 },
  { id:"b2-18", topic:"bai2", q:"“Chiến tranh lạnh” là gì?", options:["Chính sách thù địch, căng thẳng giữa Mỹ và Liên Xô, không dùng vũ lực trực tiếp","Một cuộc chiến tranh quân sự trực tiếp","Một cuộc chiến tranh kinh tế giữa các nước tư bản","Một cuộc chiến tranh ở vùng cực"], answer:0 },
  { id:"b2-19", topic:"bai2", q:"Nguyên nhân chính dẫn đến Chiến tranh lạnh là gì?", options:["Sự đối lập về mục tiêu và chiến lược giữa Mỹ và Liên Xô","Mâu thuẫn về thuộc địa","Chiến tranh thương mại","Sự suy yếu của châu Âu"], answer:0 },
  { id:"b2-20", topic:"bai2", q:"Hệ quả lớn nhất của Chiến tranh lạnh đối với thế giới là gì?", options:["Thế giới luôn căng thẳng, chạy đua vũ trang, nguy cơ chiến tranh hạt nhân","Thế giới hòa bình hoàn toàn","Chủ nghĩa thực dân phục hồi","Liên hợp quốc giải thể"], answer:0 },

  /* ============ BÀI 3: TRẬT TỰ THẾ GIỚI SAU CHIẾN TRANH LẠNH (20 câu) ============ */
  { id:"b3-01", topic:"bai3", q:"Sự kiện nào được xem là mốc chính thức tuyên bố chấm dứt Chiến tranh lạnh?", options:["Cuộc gặp không chính thức tại Malta (12/1989)","Liên Xô tan rã (1991)","Bức tường Berlin sụp đổ (1989)","Hiệp định Pari về Việt Nam (1973)"], answer:0 },
  { id:"b3-02", topic:"bai3", q:"Cuộc gặp gỡ không chính thức tại Malta (12/1989) diễn ra giữa hai nhà lãnh đạo nào?", options:["Reagan và Brezhnev","Bush (cha) và Gorbachev","Nixon và Khrushchev","Bush (cha) và Yeltsin"], answer:1 },
  { id:"b3-03", topic:"bai3", q:"Liên bang Xô viết chính thức tan rã vào năm nào?", options:["1989","1990","1991","1993"], answer:2 },
  { id:"b3-04", topic:"bai3", q:"Sau khi Chiến tranh lạnh chấm dứt, trật tự thế giới có xu hướng phát triển theo hướng nào?", options:["Đơn cực do Mỹ chi phối tuyệt đối","Đa cực, nhiều trung tâm quyền lực","Trở lại lưỡng cực như trước","Không hình thành trật tự rõ ràng"], answer:1 },
  { id:"b3-05", topic:"bai3", q:"Trong trật tự thế giới sau Chiến tranh lạnh, yếu tố nào là trọng tâm trong chiến lược phát triển của nhiều quốc gia?", options:["Sức mạnh quân sự","Sức mạnh tổng hợp quốc gia, kinh tế là trọng tâm","Mở rộng lãnh thổ","Chạy đua vũ trang hạt nhân"], answer:1 },
  { id:"b3-06", topic:"bai3", q:"Sau khi Liên Xô tan rã, Liên bang Nga đảm nhận vị trí nào tại Hội đồng Bảo an Liên hợp quốc?", options:["Ủy viên không thường trực","Ủy viên thường trực (kế tục Liên Xô)","Quan sát viên","Không còn là thành viên"], answer:1 },
  { id:"b3-07", topic:"bai3", q:"Đặc điểm nổi bật của quan hệ quốc tế trong những năm đầu sau Chiến tranh lạnh là gì?", options:["Hòa bình tuyệt đối, không còn xung đột","Vừa hợp tác vừa cạnh tranh giữa các nước lớn, xen lẫn xung đột cục bộ","Đối đầu quân sự trực tiếp giữa các siêu cường","Trở lại nguyên trạng trật tự hai cực"], answer:1 },
  { id:"b3-08", topic:"bai3", q:"Xu thế toàn cầu hóa diễn ra mạnh mẽ nhất từ khoảng thời gian nào?", options:["Những năm 1970","Những năm 1980, đặc biệt từ đầu thập niên 90 thế kỷ XX","Ngay sau Chiến tranh thế giới thứ nhất","Ngay sau khi Liên hợp quốc thành lập"], answer:1 },
  { id:"b3-09", topic:"bai3", q:"Trong xu thế đa cực hóa sau Chiến tranh lạnh, nhận định nào KHÔNG đúng?", options:["Trung Quốc trở thành một trung tâm quyền lực đáng kể","Liên minh châu Âu (EU) là một trung tâm kinh tế lớn","Nhật Bản vẫn là một cường quốc kinh tế","Một siêu cường duy nhất chi phối tuyệt đối toàn bộ thế giới"], answer:3 },
  { id:"b3-10", topic:"bai3", q:"Sau Chiến tranh lạnh, khu vực nào vẫn xảy ra nhiều xung đột, khủng bố?", options:["Trung Đông, châu Phi, một số nước Đông Âu","Bắc Mỹ","Tây Âu","Australia"], answer:0 },
  { id:"b3-11", topic:"bai3", q:"Xu thế chung của thế giới sau Chiến tranh lạnh là gì?", options:["Hòa bình, ổn định, hợp tác và phát triển","Chiến tranh và xung đột liên miên","Đóng cửa, biệt lập","Quay lại chủ nghĩa thực dân"], answer:0 },
  { id:"b3-12", topic:"bai3", q:"Tổ chức nào ra đời sau Chiến tranh lạnh nhằm thúc đẩy hợp tác khu vực châu Á - Thái Bình Dương?", options:["APEC","NATO","SEATO","CENTO"], answer:0 },
  { id:"b3-13", topic:"bai3", q:"Trong bối cảnh toàn cầu hóa, Việt Nam cần làm gì để phát triển?", options:["Chủ động hội nhập, giữ vững độc lập, tự chủ","Đóng cửa với thế giới","Chỉ dựa vào một cường quốc","Chạy đua vũ trang"], answer:0 },
  { id:"b3-14", topic:"bai3", q:"Xu thế “đa phương hóa, đa dạng hóa” quan hệ quốc tế của Việt Nam bắt đầu từ khi nào?", options:["Sau Đổi mới 1986","Sau 1975","Sau 1945","Sau 2000"], answer:0 },
  { id:"b3-15", topic:"bai3", q:"Toàn cầu hóa có tác động gì đến các nước đang phát triển?", options:["Vừa tạo cơ hội vừa đặt ra thách thức","Chỉ có cơ hội","Chỉ có thách thức","Không ảnh hưởng gì"], answer:0 },
  { id:"b3-16", topic:"bai3", q:"Tổ chức thương mại thế giới (WTO) được thành lập năm nào?", options:["1995","2000","1986","2007"], answer:0 },
  { id:"b3-17", topic:"bai3", q:"Việt Nam gia nhập WTO vào năm nào?", options:["2007","1995","2000","2010"], answer:0 },
  { id:"b3-18", topic:"bai3", q:"Sau Chiến tranh lạnh, Mỹ có còn là siêu cường duy nhất không?", options:["Không, mà là một trong các trung tâm quyền lực","Có, Mỹ vẫn chi phối toàn cầu","Không, Mỹ đã suy yếu hoàn toàn","Có, Mỹ là siêu cường duy nhất"], answer:0 },
  { id:"b3-19", topic:"bai3", q:"Các trung tâm kinh tế - chính trị lớn của thế giới sau Chiến tranh lạnh gồm:", options:["Mỹ, EU, Nhật Bản, Nga, Trung Quốc","Mỹ, Anh, Pháp, Đức","Mỹ, Ấn Độ, Brazil","Mỹ, Canada, Mexico"], answer:0 },
  { id:"b3-20", topic:"bai3", q:"Bài học từ trật tự thế giới sau Chiến tranh lạnh cho Việt Nam là gì?", options:["Giữ vững độc lập, tự chủ, đa phương hóa, đa dạng hóa","Dựa vào một cường quốc","Chạy đua vũ trang","Đóng cửa kinh tế"], answer:0 },

  /* ============ BÀI 4: ASEAN — HÌNH THÀNH VÀ PHÁT TRIỂN (20 câu) ============ */
  { id:"b4-01", topic:"bai4", q:"Hiệp hội các quốc gia Đông Nam Á (ASEAN) được thành lập vào ngày tháng năm nào?", options:["8/8/1967","8/8/1976","28/7/1995","31/12/2015"], answer:0 },
  { id:"b4-02", topic:"bai4", q:"ASEAN được thành lập tại thành phố nào?", options:["Jakarta, Indonesia","Bangkok, Thái Lan","Manila, Philippines","Kuala Lumpur, Malaysia"], answer:1 },
  { id:"b4-03", topic:"bai4", q:"Văn kiện nào đánh dấu sự ra đời của ASEAN?", options:["Tuyên bố Bangkok","Hiệp ước Bali","Hiến chương ASEAN","Tuyên bố Cebu"], answer:0 },
  { id:"b4-04", topic:"bai4", q:"ASEAN được thành lập với bao nhiêu quốc gia sáng lập?", options:["4","5","6","10"], answer:1 },
  { id:"b4-05", topic:"bai4", q:"Quốc gia nào sau đây KHÔNG phải là thành viên sáng lập ASEAN?", options:["Indonesia","Malaysia","Việt Nam","Philippines"], answer:2 },
  { id:"b4-06", topic:"bai4", q:"Năm nước sáng lập ASEAN gồm những nước nào?", options:["Indonesia, Malaysia, Philippines, Singapore, Thái Lan","Việt Nam, Lào, Campuchia, Myanmar, Brunei","Indonesia, Việt Nam, Lào, Campuchia, Thái Lan","Malaysia, Singapore, Brunei, Việt Nam, Lào"], answer:0 },
  { id:"b4-07", topic:"bai4", q:"Việt Nam chính thức gia nhập ASEAN vào thời gian nào?", options:["28/7/1995","8/8/1967","23/7/1997","30/4/1999"], answer:0 },
  { id:"b4-08", topic:"bai4", q:"Hai quốc gia nào gia nhập ASEAN cùng trong năm 1997?", options:["Lào và Myanmar","Lào và Campuchia","Myanmar và Campuchia","Việt Nam và Lào"], answer:0 },
  { id:"b4-09", topic:"bai4", q:"Campuchia chính thức trở thành thành viên ASEAN vào năm nào?", options:["1995","1997","1999","2003"], answer:2 },
  { id:"b4-10", topic:"bai4", q:"Quốc gia nào gia nhập ASEAN năm 1984, không lâu sau khi giành độc lập?", options:["Brunei","Đông Timor","Singapore","Lào"], answer:0 },
  { id:"b4-11", topic:"bai4", q:"Mục tiêu ban đầu khi thành lập ASEAN năm 1967 là gì?", options:["Thúc đẩy hợp tác kinh tế, văn hóa, hòa bình và ổn định khu vực","Thành lập liên minh quân sự chống một cường quốc","Sáp nhập các nước thành viên thành một quốc gia","Cạnh tranh trực tiếp với Liên hợp quốc"], answer:0 },
  { id:"b4-12", topic:"bai4", q:"Hiệp ước Bali (1976) có ý nghĩa như thế nào đối với ASEAN?", options:["Xác định các nguyên tắc cơ bản trong quan hệ giữa các nước thành viên","Thành lập đồng tiền chung ASEAN","Kết nạp thêm 5 thành viên mới","Giải thể ASEAN cũ để thành lập lại"], answer:0 },
  { id:"b4-13", topic:"bai4", q:"ASEAN theo đuổi nguyên tắc nào trong việc ra quyết định?", options:["Đa số áp đảo","Đồng thuận (nhất trí)","Do nước lớn nhất quyết định","Bỏ phiếu theo dân số"], answer:1 },
  { id:"b4-14", topic:"bai4", q:"Đâu KHÔNG phải là nguyên tắc hoạt động của ASEAN?", options:["Tôn trọng độc lập, chủ quyền","Không can thiệp vào nội bộ","Giải quyết tranh chấp bằng hòa bình","Can thiệp quân sự vào nước thành viên"], answer:3 },
  { id:"b4-15", topic:"bai4", q:"ASEAN hiện có bao nhiêu thành viên?", options:["10","5","8","12"], answer:0 },
  { id:"b4-16", topic:"bai4", q:"Đông Timor hiện có phải thành viên chính thức của ASEAN không?", options:["Chưa, đang trong quá trình xem xét","Đã là thành viên từ 2002","Đã là thành viên từ 2011","Không bao giờ gia nhập"], answer:0 },
  { id:"b4-17", topic:"bai4", q:"Việc Việt Nam gia nhập ASEAN năm 1995 có ý nghĩa như thế nào?", options:["Góp phần củng cố hòa bình, ổn định khu vực và mở rộng hợp tác quốc tế","Chấm dứt quan hệ với các nước ngoài khu vực","Việt Nam trở thành nước dẫn đầu ASEAN ngay lập tức","ASEAN giải thể để lập tổ chức mới"], answer:0 },
  { id:"b4-18", topic:"bai4", q:"ASEAN được thành lập trong bối cảnh nào của khu vực Đông Nam Á?", options:["Căng thẳng, đối đầu, cần hợp tác để ổn định khu vực","Hòa bình, thịnh vượng","Đã thống nhất thành một khối","Không có nhu cầu hợp tác"], answer:0 },
  { id:"b4-19", topic:"bai4", q:"“ASEAN 10” hoàn thành vào năm nào?", options:["1999","1995","1997","2003"], answer:0 },
  { id:"b4-20", topic:"bai4", q:"Ý nghĩa quan trọng nhất của việc ASEAN kết nạp đủ 10 nước Đông Nam Á là gì?", options:["Hoàn thành ý tưởng về một Đông Nam Á thống nhất, hợp tác","Chấm dứt mọi xung đột trên thế giới","Trở thành tổ chức lớn nhất thế giới","Thay thế Liên hợp quốc"], answer:0 },

  /* ============ BÀI 5: CỘNG ĐỒNG ASEAN (20 câu) ============ */
  { id:"b5-01", topic:"bai5", q:"Hiến chương ASEAN được ký kết vào năm nào?", options:["1967","1976","2007","2015"], answer:2 },
  { id:"b5-02", topic:"bai5", q:"Hiến chương ASEAN chính thức có hiệu lực từ khi nào?", options:["12/2007","12/2008","12/2009","1/2010"], answer:1 },
  { id:"b5-03", topic:"bai5", q:"Cộng đồng ASEAN chính thức được thành lập vào ngày nào?", options:["8/8/2015","31/12/2015","22/11/2015","1/1/2016"], answer:1 },
  { id:"b5-04", topic:"bai5", q:"Cộng đồng ASEAN được xây dựng trên bao nhiêu trụ cột chính?", options:["2","3","4","5"], answer:1 },
  { id:"b5-05", topic:"bai5", q:"Ba trụ cột của Cộng đồng ASEAN gồm những trụ cột nào?", options:["Chính trị–An ninh, Kinh tế, Văn hóa–Xã hội","Kinh tế, Quân sự, Ngoại giao","Chính trị, Văn hóa, Môi trường","An ninh, Giáo dục, Y tế"], answer:0 },
  { id:"b5-06", topic:"bai5", q:"Cộng đồng Chính trị - An ninh ASEAN (APSC) nhằm mục tiêu gì?", options:["Đưa ASEAN thành khu vực hòa bình, ổn định, giải quyết tranh chấp bằng hòa bình","Thành lập liên minh quân sự","Xâm lược các nước láng giềng","Chạy đua vũ trang"], answer:0 },
  { id:"b5-07", topic:"bai5", q:"Cộng đồng Kinh tế ASEAN (AEC) nhằm mục tiêu gì?", options:["Tạo thị trường chung, cơ sở sản xuất chung, thúc đẩy thương mại đầu tư","Xóa bỏ biên giới quốc gia","Sử dụng một đồng tiền chung","Thành lập chính phủ chung"], answer:0 },
  { id:"b5-08", topic:"bai5", q:"Cộng đồng Văn hóa - Xã hội ASEAN (ASCC) nhằm mục tiêu gì?", options:["Nâng cao chất lượng cuộc sống, phát triển văn hóa, bảo vệ môi trường","Quân sự hóa khu vực","Chỉ phát triển kinh tế","Thành lập liên minh thuế quan"], answer:0 },
  { id:"b5-09", topic:"bai5", q:"Hiến chương ASEAN có ý nghĩa như thế nào?", options:["Tạo cơ sở pháp lý, thể chế cho ASEAN hoạt động hiệu quả hơn","Giải thể ASEAN","Xóa bỏ các nguyên tắc cũ","Chỉ có tính tượng trưng"], answer:0 },
  { id:"b5-10", topic:"bai5", q:"Tuyên bố Nhân quyền ASEAN (AHRD) được thông qua năm nào?", options:["2007","2012","2015","2020"], answer:1 },
  { id:"b5-11", topic:"bai5", q:"Tầm nhìn ASEAN 2020 được thông qua năm nào?", options:["1997","2007","2015","2020"], answer:0 },
  { id:"b5-12", topic:"bai5", q:"Tầm nhìn Cộng đồng ASEAN 2025 được thông qua năm nào?", options:["2007","2015","2020","2025"], answer:1 },
  { id:"b5-13", topic:"bai5", q:"Thách thức lớn nhất của Cộng đồng ASEAN hiện nay là gì?", options:["Chênh lệch trình độ phát triển giữa các nước thành viên","Không có thành viên nào","Không có Hiến chương","Không có mục tiêu chung"], answer:0 },
  { id:"b5-14", topic:"bai5", q:"ASEAN hiện có quan hệ đối tác chiến lược với những nước lớn nào?", options:["Trung Quốc, Mỹ, Nhật Bản, Hàn Quốc, Ấn Độ, Nga, Australia","Chỉ với Mỹ","Chỉ với Trung Quốc","Chỉ với Nhật Bản"], answer:0 },
  { id:"b5-15", topic:"bai5", q:"Việt Nam đảm nhận vai trò Chủ tịch ASEAN vào năm nào?", options:["2010 và 2020","1995 và 2000","2005 và 2015","2015 và 2025"], answer:0 },
  { id:"b5-16", topic:"bai5", q:"Cộng đồng ASEAN ra đời đánh dấu bước phát triển như thế nào của ASEAN?", options:["Từ hợp tác lỏng lẻo sang liên kết chặt chẽ, toàn diện","Từ hợp tác chặt sang lỏng lẻo","Từ quân sự sang kinh tế","Từ kinh tế sang quân sự"], answer:0 },
  { id:"b5-17", topic:"bai5", q:"Mục tiêu tổng quát của Cộng đồng ASEAN là gì?", options:["Hòa bình, ổn định, thịnh vượng chung","Chỉ phát triển kinh tế","Chỉ hợp tác quân sự","Chỉ bảo vệ môi trường"], answer:0 },
  { id:"b5-18", topic:"bai5", q:"ASEAN ký Hiệp ước Thân thiện và Hợp tác ở Đông Nam Á (TAC) năm nào?", options:["1976","1995","2007","2015"], answer:0 },
  { id:"b5-19", topic:"bai5", q:"Hiệp ước TAC (1976) có ý nghĩa như thế nào?", options:["Là cơ sở pháp lý cho quan hệ hòa bình giữa các nước trong và ngoài khu vực","Thành lập liên minh quân sự","Xóa bỏ biên giới","Thành lập chính phủ chung"], answer:0 },
  { id:"b5-20", topic:"bai5", q:"Vai trò của ASEAN trên trường quốc tế ngày càng được nâng cao nhờ đâu?", options:["Vị trí chiến lược, kinh tế phát triển, hợp tác khu vực hiệu quả","Sức mạnh quân sự","Sở hữu vũ khí hạt nhân","Dân số đông"], answer:0 },

  /* ============ BÀI 6: CÁCH MẠNG THÁNG TÁM 1945 (20 câu) ============ */
  { id:"b6-01", topic:"bai6", q:"Cách mạng tháng Tám năm 1945 nổ ra trong bối cảnh lịch sử nào?", options:["Phát xít Nhật đầu hàng Đồng minh","Pháp đảo chính Nhật","Chiến tranh thế giới thứ hai bùng nổ","Liên Xô tấn công Nhật"], answer:0 },
  { id:"b6-02", topic:"bai6", q:"Sự kiện nào đánh dấu Cách mạng tháng Tám 1945 giành thắng lợi hoàn toàn?", options:["Nhật đảo chính Pháp","Khởi nghĩa giành chính quyền ở Hà Nội","Bác Hồ đọc Tuyên ngôn Độc lập","Pháp ký Hiệp định Sơ bộ"], answer:2 },
  { id:"b6-03", topic:"bai6", q:"Hội nghị nào đã quyết định phát động Tổng khởi nghĩa giành chính quyền trong cả nước?", options:["Hội nghị Trung ương 8 (5/1941)","Hội nghị Tân Trào (8/1945)","Hội nghị Bắc Pó","Hội nghị Pắc Bó"], answer:1 },
  { id:"b6-04", topic:"bai6", q:"Ngày 2/9/1945, tại Quảng trường Ba Đình, Chủ tịch Hồ Chí Minh đã làm gì?", options:["Đọc Tuyên ngôn Độc lập, khai sinh nước Việt Nam Dân chủ Cộng hòa","Ký Hiệp định Sơ bộ với Pháp","Thành lập Đảng Cộng sản Việt Nam","Phát động toàn quốc kháng chiến"], answer:0 },
  { id:"b6-05", topic:"bai6", q:"Lực lượng nào đóng vai trò chủ yếu trong Cách mạng tháng Tám 1945?", options:["Quân đội chính quy","Quần chúng nhân dân, đặc biệt là công nhân và nông dân","Tầng lớp trí thức","Giai cấp tư sản dân tộc"], answer:1 },
  { id:"b6-06", topic:"bai6", q:"Nguyên nhân khách quan tạo điều kiện thuận lợi cho Cách mạng tháng Tám?", options:["Phát xít Nhật đầu hàng Đồng minh (8/1945)","Pháp đảo chính Nhật","Mỹ ném bom nguyên tử xuống Nhật","Liên Xô tấn công Nhật"], answer:0 },
  { id:"b6-07", topic:"bai6", q:"Bài học kinh nghiệm lớn nhất của Cách mạng tháng Tám 1945 là gì?", options:["Nắm bắt thời cơ, phát huy sức mạnh đoàn kết toàn dân tộc","Chỉ dựa vào sự giúp đỡ của quốc tế","Đấu tranh vũ trang là duy nhất","Chờ đợi thời cơ chín muồi"], answer:0 },
  { id:"b6-08", topic:"bai6", q:"Khởi nghĩa giành chính quyền ở Hà Nội diễn ra vào ngày nào?", options:["19/8/1945","23/8/1945","25/8/1945","2/9/1945"], answer:0 },
  { id:"b6-09", topic:"bai6", q:"Khởi nghĩa giành chính quyền ở Sài Gòn diễn ra vào ngày nào?", options:["19/8/1945","23/8/1945","25/8/1945","2/9/1945"], answer:2 },
  { id:"b6-10", topic:"bai6", q:"Vua Bảo Đại thoái vị vào ngày nào?", options:["30/8/1945","2/9/1945","19/8/1945","25/8/1945"], answer:0 },
  { id:"b6-11", topic:"bai6", q:"Cách mạng tháng Tám 1945 diễn ra trong bao lâu?", options:["15 ngày","1 tháng","3 tháng","1 năm"], answer:0 },
  { id:"b6-12", topic:"bai6", q:"Đâu là nguyên nhân chủ quan quyết định thắng lợi của Cách mạng tháng Tám?", options:["Sự lãnh đạo đúng đắn của Đảng và Chủ tịch Hồ Chí Minh","Nhật đầu hàng Đồng minh","Mỹ ném bom nguyên tử","Liên Xô giúp đỡ"], answer:0 },
  { id:"b6-13", topic:"bai6", q:"Ý nghĩa lịch sử to lớn nhất của Cách mạng tháng Tám 1945 là gì?", options:["Đập tan ách thống trị của thực dân, phong kiến, lập nên nước Việt Nam Dân chủ Cộng hòa","Chấm dứt Chiến tranh thế giới thứ hai","Giúp Việt Nam gia nhập Liên hợp quốc","Xóa bỏ hoàn toàn đói nghèo"], answer:0 },
  { id:"b6-14", topic:"bai6", q:"Mặt trận nào được thành lập năm 1941 để tập hợp lực lượng cách mạng?", options:["Việt Nam Độc lập Đồng minh (Việt Minh)","Mặt trận Dân chủ Đông Dương","Mặt trận Tổ quốc Việt Nam","Mặt trận Liên Việt"], answer:0 },
  { id:"b6-15", topic:"bai6", q:"Cao trào kháng Nhật cứu nước diễn ra trong khoảng thời gian nào?", options:["Tháng 3 đến tháng 8/1945","Tháng 9/1940 đến tháng 3/1945","Tháng 1 đến tháng 5/1945","Tháng 8/1945"], answer:0 },
  { id:"b6-16", topic:"bai6", q:"Khẩu hiệu “Phá kho thóc, giải quyết nạn đói” gắn với sự kiện nào?", options:["Cao trào kháng Nhật cứu nước (1945)","Khởi nghĩa Bắc Sơn","Khởi nghĩa Nam Kỳ","Đồng khởi 1960"], answer:0 },
  { id:"b6-17", topic:"bai6", q:"Ngày 9/3/1945 diễn ra sự kiện gì ở Đông Dương?", options:["Nhật đảo chính Pháp","Pháp đảo chính Nhật","Nhật đầu hàng Đồng minh","Pháp rút khỏi Đông Dương"], answer:0 },
  { id:"b6-18", topic:"bai6", q:"Nguyên nhân trực tiếp dẫn đến Nhật đảo chính Pháp (9/3/1945) là gì?", options:["Nhật lo sợ Pháp sẽ đánh sau lưng khi Đồng minh đổ bộ","Pháp tấn công Nhật trước","Đức đầu hàng","Liên Xô tuyên chiến với Nhật"], answer:0 },
  { id:"b6-19", topic:"bai6", q:"Đội Việt Nam Tuyên truyền Giải phóng quân được thành lập vào ngày nào?", options:["22/12/1944","19/8/1945","2/9/1945","3/2/1930"], answer:0 },
  { id:"b6-20", topic:"bai6", q:"Cách mạng tháng Tám 1945 thắng lợi đã mở ra kỷ nguyên mới nào cho dân tộc Việt Nam?", options:["Kỷ nguyên độc lập, tự do và chủ nghĩa xã hội","Kỷ nguyên phong kiến","Kỷ nguyên thuộc địa","Kỷ nguyên chiến tranh"], answer:0 },

  /* ============ BÀI 7: KHÁNG CHIẾN CHỐNG PHÁP (20 câu) ============ */
  { id:"b7-01", topic:"bai7", q:"Cuộc kháng chiến chống Pháp của nhân dân ta chính thức bắt đầu bằng sự kiện nào?", options:["Pháp tấn công Đà Nẵng (1858)","Chủ tịch Hồ Chí Minh ra Lời kêu gọi toàn quốc kháng chiến (12/1946)","Hiệp định Sơ bộ 1946","Chiến dịch Việt Bắc 1947"], answer:1 },
  { id:"b7-02", topic:"bai7", q:"Chiến dịch nào đã kết thúc thắng lợi cuộc kháng chiến chống Pháp?", options:["Chiến dịch Việt Bắc","Chiến dịch Biên giới","Chiến dịch Điện Biên Phủ","Chiến dịch Tây Bắc"], answer:2 },
  { id:"b7-03", topic:"bai7", q:"Hiệp định Genève về Đông Dương được ký kết vào năm nào?", options:["1950","1954","1956","1962"], answer:1 },
  { id:"b7-04", topic:"bai7", q:"Chiến dịch Điện Biên Phủ diễn ra trong bao nhiêu ngày đêm?", options:["30 ngày","56 ngày đêm","75 ngày","100 ngày"], answer:1 },
  { id:"b7-05", topic:"bai7", q:"Đường lối kháng chiến của Đảng ta trong kháng chiến chống Pháp là gì?", options:["Toàn dân, toàn diện, trường kỳ, tự lực cánh sinh","Đánh nhanh thắng nhanh","Chỉ dựa vào quân đội chính quy","Chờ đợi quốc tế can thiệp"], answer:0 },
  { id:"b7-06", topic:"bai7", q:"Chiến thắng nào được coi là mốc mở đầu thắng lợi của quân ta trong kháng chiến chống Pháp?", options:["Việt Bắc 1947","Biên giới 1950","Điện Biên Phủ 1954","Tây Bắc 1952"], answer:1 },
  { id:"b7-07", topic:"bai7", q:"Tướng Pháp nào đã bị bắt sống tại Điện Biên Phủ?", options:["Đờ Cát (De Castries)","Na-va (Navarre)","Bô-la-e (Bollaert)","Sao (Salan)"], answer:0 },
  { id:"b7-08", topic:"bai7", q:"Hiệp định Genève 1954 quy định vĩ tuyến nào là giới tuyến quân sự tạm thời ở Việt Nam?", options:["Vĩ tuyến 17","Vĩ tuyến 16","Vĩ tuyến 18","Vĩ tuyến 20"], answer:0 },
  { id:"b7-09", topic:"bai7", q:"Chiến dịch Việt Bắc diễn ra vào năm nào?", options:["1946","1947","1950","1954"], answer:1 },
  { id:"b7-10", topic:"bai7", q:"Chiến dịch Biên giới diễn ra vào năm nào?", options:["1947","1950","1952","1954"], answer:1 },
  { id:"b7-11", topic:"bai7", q:"Chiến thắng nào đã khai thông biên giới Việt - Trung, mở rộng quan hệ với các nước XHCN?", options:["Việt Bắc 1947","Biên giới 1950","Tây Bắc 1952","Điện Biên Phủ 1954"], answer:1 },
  { id:"b7-12", topic:"bai7", q:"Kế hoạch Na-va (1953) của Pháp nhằm mục đích gì?", options:["Xoay chuyển cục diện chiến tranh, giành thắng lợi quân sự quyết định","Rút quân khỏi Đông Dương","Chia cắt Việt Nam","Thành lập chính phủ bù nhìn"], answer:0 },
  { id:"b7-13", topic:"bai7", q:"Pháp xây dựng Điện Biên Phủ thành tập đoàn cứ điểm mạnh nhất Đông Dương nhằm mục đích gì?", options:["Thu hút và tiêu diệt chủ lực ta","Bảo vệ biên giới","Xây dựng căn cứ kinh tế","Chuẩn bị rút quân"], answer:0 },
  { id:"b7-14", topic:"bai7", q:"Chiến thắng Điện Biên Phủ 1954 có ý nghĩa quốc tế như thế nào?", options:["Cổ vũ phong trào giải phóng dân tộc trên thế giới","Chấm dứt Chiến tranh lạnh","Làm sụp đổ chủ nghĩa thực dân trên toàn thế giới ngay lập tức","Giúp Việt Nam gia nhập Liên hợp quốc"], answer:0 },
  { id:"b7-15", topic:"bai7", q:"Hiệp định Genève 1954 quy định bao nhiêu ngày để chuyển quân tập kết?", options:["100 ngày","300 ngày","500 ngày","30 ngày"], answer:1 },
  { id:"b7-16", topic:"bai7", q:"Sau Hiệp định Genève 1954, Mỹ đã làm gì ở miền Nam Việt Nam?", options:["Dựng chính quyền tay sai Ngô Đình Diệm, phá hoại Hiệp định","Rút hết quân khỏi Việt Nam","Ủng hộ Việt Nam thống nhất","Chuyển giao miền Nam cho Pháp"], answer:0 },
  { id:"b7-17", topic:"bai7", q:"Đại hội đại biểu toàn quốc lần thứ II của Đảng (1951) đã đổi tên Đảng thành gì?", options:["Đảng Lao động Việt Nam","Đảng Cộng sản Đông Dương","Đảng Cộng sản Việt Nam","Đảng Nhân dân Cách mạng"], answer:0 },
  { id:"b7-18", topic:"bai7", q:"Chiến thắng nào đã đánh bại hoàn toàn kế hoạch Na-va?", options:["Điện Biên Phủ 1954","Biên giới 1950","Việt Bắc 1947","Tây Bắc 1952"], answer:0 },
  { id:"b7-19", topic:"bai7", q:"Nguyên nhân quyết định thắng lợi của cuộc kháng chiến chống Pháp là gì?", options:["Sự lãnh đạo đúng đắn của Đảng, lòng yêu nước của nhân dân, đoàn kết quốc tế","Pháp suy yếu","Mỹ giúp đỡ Việt Nam","Liên Xô trực tiếp tham chiến"], answer:0 },
  { id:"b7-20", topic:"bai7", q:"Bài học kinh nghiệm lớn nhất từ kháng chiến chống Pháp là gì?", options:["Kết hợp sức mạnh dân tộc với sức mạnh thời đại, phát huy tinh thần đoàn kết","Chỉ dựa vào quân đội chính quy","Chỉ dựa vào quốc tế","Chạy đua vũ trang"], answer:0 },

  /* ============ BÀI 8: KHÁNG CHIẾN CHỐNG MỸ (20 câu) ============ */
  { id:"b8-01", topic:"bai8", q:"Cuộc kháng chiến chống Mỹ cứu nước của nhân dân ta kéo dài trong bao nhiêu năm?", options:["20 năm (1955–1975)","21 năm (1954–1975)","15 năm (1960–1975)","10 năm (1965–1975)"], answer:1 },
  { id:"b8-02", topic:"bai8", q:"Chiến thắng nào đánh dấu bước ngoặt của cuộc kháng chiến chống Mỹ?", options:["Chiến thắng Ấp Bắc","Chiến thắng Vạn Tường","Tổng tiến công Mậu Thân 1968","Chiến thắng Điện Biên Phủ trên không 1972"], answer:1 },
  { id:"b8-03", topic:"bai8", q:"Hiệp định Pari về Việt Nam được ký kết vào năm nào?", options:["1968","1970","1973","1975"], answer:2 },
  { id:"b8-04", topic:"bai8", q:"Chiến dịch Hồ Chí Minh kết thúc vào ngày nào?", options:["30/4/1975","1/5/1975","2/9/1975","26/3/1975"], answer:0 },
  { id:"b8-05", topic:"bai8", q:"“Điện Biên Phủ trên không” là chiến thắng của quân dân miền Bắc chống lại máy bay nào của Mỹ?", options:["B-52","F-4","B-1","F-16"], answer:0 },
  { id:"b8-06", topic:"bai8", q:"Chiến lược “Chiến tranh đặc biệt” của Mỹ được thực hiện ở miền Nam giai đoạn nào?", options:["1954–1960","1961–1965","1965–1968","1969–1972"], answer:1 },
  { id:"b8-07", topic:"bai8", q:"Sự kiện nào buộc Mỹ phải tuyên bố “Mỹ hóa trở lại” chiến tranh?", options:["Tổng tiến công Mậu Thân 1968","Hiệp định Pari 1973","Chiến thắng Điện Biên Phủ trên không 1972","Chiến thắng Ấp Bắc 1963"], answer:0 },
  { id:"b8-08", topic:"bai8", q:"Ý nghĩa lớn nhất của cuộc kháng chiến chống Mỹ cứu nước là gì?", options:["Giải phóng hoàn toàn miền Nam, thống nhất đất nước","Chấm dứt ách thống trị của Pháp","Mở rộng quan hệ với các nước XHCN","Gia nhập ASEAN"], answer:0 },
  { id:"b8-09", topic:"bai8", q:"Chiến lược “Chiến tranh cục bộ” của Mỹ diễn ra trong giai đoạn nào?", options:["1961–1965","1965–1968","1969–1972","1973–1975"], answer:1 },
  { id:"b8-10", topic:"bai8", q:"Chiến lược “Việt Nam hóa chiến tranh” diễn ra trong giai đoạn nào?", options:["1961–1965","1965–1968","1969–1973","1973–1975"], answer:2 },
  { id:"b8-11", topic:"bai8", q:"Chiến thắng Ấp Bắc (1963) có ý nghĩa như thế nào?", options:["Chứng minh quân dân miền Nam có thể đánh bại “Chiến tranh đặc biệt”","Kết thúc chiến tranh","Mỹ rút quân","Miền Nam được giải phóng"], answer:0 },
  { id:"b8-12", topic:"bai8", q:"Chiến thắng Vạn Tường (1965) có ý nghĩa như thế nào?", options:["Chứng minh quân dân ta có thể đánh bại “Chiến tranh cục bộ”","Kết thúc chiến tranh","Mỹ rút quân","Miền Nam được giải phóng"], answer:0 },
  { id:"b8-13", topic:"bai8", q:"Cuộc Tổng tiến công và nổi dậy Tết Mậu Thân 1968 diễn ra trong bao lâu?", options:["1 tháng","3 tháng","6 tháng","1 năm"], answer:1 },
  { id:"b8-14", topic:"bai8", q:"Hiệp định Pari 1973 quy định điều gì quan trọng nhất?", options:["Mỹ rút hết quân khỏi miền Nam Việt Nam","Miền Nam được giải phóng","Việt Nam thống nhất","Mỹ bồi thường chiến tranh"], answer:0 },
  { id:"b8-15", topic:"bai8", q:"Sau Hiệp định Pari 1973, Mỹ đã làm gì ở miền Nam?", options:["Vẫn tiếp tục viện trợ cho chính quyền Sài Gòn, phá hoại Hiệp định","Rút hết quân và viện trợ","Ủng hộ Việt Nam thống nhất","Chuyển giao miền Nam cho miền Bắc"], answer:0 },
  { id:"b8-16", topic:"bai8", q:"Chiến dịch Tây Nguyên (3/1975) mở đầu cho cuộc Tổng tiến công và nổi dậy mùa Xuân 1975, giải phóng thành phố nào?", options:["Buôn Ma Thuột","Đà Nẵng","Sài Gòn","Huế"], answer:0 },
  { id:"b8-17", topic:"bai8", q:"Chiến dịch Huế - Đà Nẵng diễn ra vào thời gian nào?", options:["Tháng 3/1975","Tháng 4/1975","Tháng 1/1975","Tháng 5/1975"], answer:0 },
  { id:"b8-18", topic:"bai8", q:"Chiến dịch Hồ Chí Minh bắt đầu vào ngày nào?", options:["26/4/1975","30/4/1975","1/5/1975","2/9/1975"], answer:0 },
  { id:"b8-19", topic:"bai8", q:"Nguyên nhân quyết định thắng lợi của kháng chiến chống Mỹ là gì?", options:["Sự lãnh đạo của Đảng, tinh thần yêu nước, đoàn kết quốc tế","Mỹ suy yếu","Liên Xô trực tiếp tham chiến","Trung Quốc giúp đỡ"], answer:0 },
  { id:"b8-20", topic:"bai8", q:"Bài học lớn nhất từ kháng chiến chống Mỹ là gì?", options:["Kết hợp sức mạnh dân tộc với sức mạnh thời đại, phát huy nội lực","Chỉ dựa vào quốc tế","Chỉ dựa vào quân sự","Chạy đua vũ trang"], answer:0 },

  /* ============ BÀI 9: VIỆT NAM SAU 1975 (20 câu) ============ */
  { id:"b9-01", topic:"bai9", q:"Sau ngày 30/4/1975, Việt Nam bước vào giai đoạn lịch sử nào?", options:["Xây dựng và bảo vệ Tổ quốc","Kháng chiến chống Pháp","Kháng chiến chống Mỹ","Thời kỳ Pháp thuộc"], answer:0 },
  { id:"b9-02", topic:"bai9", q:"Quốc hội khóa VI (1976) đã có quyết định quan trọng nào?", options:["Đổi tên nước thành CHXHCN Việt Nam","Thành lập Đảng Cộng sản Việt Nam","Ký Hiệp định Pari","Gia nhập ASEAN"], answer:0 },
  { id:"b9-03", topic:"bai9", q:"Việt Nam gặp khó khăn gì sau năm 1975 trong công cuộc xây dựng đất nước?", options:["Hậu quả chiến tranh nặng nề, bị bao vây cấm vận","Được quốc tế viện trợ dồi dào","Kinh tế phát triển nhanh chóng","Không gặp khó khăn gì"], answer:0 },
  { id:"b9-04", topic:"bai9", q:"Chiến tranh biên giới Tây Nam (1978–1979) diễn ra giữa Việt Nam và lực lượng nào?", options:["Khơ-me Đỏ (Pol Pot)","Quân Pháp","Quân Mỹ","Quân Nhật"], answer:0 },
  { id:"b9-05", topic:"bai9", q:"Chiến tranh biên giới phía Bắc (1979) diễn ra giữa Việt Nam và quốc gia nào?", options:["Trung Quốc","Lào","Campuchia","Thái Lan"], answer:0 },
  { id:"b9-06", topic:"bai9", q:"Sau 1975, Việt Nam thống nhất về mặt nhà nước vào năm nào?", options:["1975","1976","1977","1980"], answer:1 },
  { id:"b9-07", topic:"bai9", q:"Đại hội Đảng lần thứ IV diễn ra năm nào?", options:["1976","1982","1986","1991"], answer:0 },
  { id:"b9-08", topic:"bai9", q:"Kế hoạch 5 năm lần thứ hai (1976–1980) đạt được kết quả gì?", options:["Đạt một số thành tựu nhưng còn nhiều hạn chế, khó khăn","Hoàn thành xuất sắc mọi chỉ tiêu","Thất bại hoàn toàn","Không có kết quả gì"], answer:0 },
  { id:"b9-09", topic:"bai9", q:"Khó khăn lớn nhất của Việt Nam sau 1975 là gì?", options:["Bị bao vây, cấm vận, cô lập về kinh tế - chính trị","Thiếu nhân lực","Thiếu đất đai","Thiếu tài nguyên"], answer:0 },
  { id:"b9-10", topic:"bai9", q:"Cuộc chiến đấu bảo vệ biên giới Tây Nam kết thúc thắng lợi vào năm nào?", options:["1975","1977","1979","1982"], answer:2 },
  { id:"b9-11", topic:"bai9", q:"Việt Nam rút quân khỏi Campuchia vào năm nào?", options:["1985","1989","1991","1995"], answer:1 },
  { id:"b9-12", topic:"bai9", q:"Quan hệ Việt - Trung bình thường hóa vào năm nào?", options:["1991","1995","2000","2007"], answer:0 },
  { id:"b9-13", topic:"bai9", q:"Quan hệ Việt - Mỹ bình thường hóa vào năm nào?", options:["1990","1995","2000","2007"], answer:1 },
  { id:"b9-14", topic:"bai9", q:"Việt Nam gia nhập ASEAN vào năm nào?", options:["1995","1997","1999","2000"], answer:0 },
  { id:"b9-15", topic:"bai9", q:"Thành tựu lớn nhất của Việt Nam trong 10 năm đầu sau thống nhất (1975–1985) là gì?", options:["Hoàn thành thống nhất đất nước về mặt nhà nước, bảo vệ biên giới","Trở thành nước công nghiệp","Gia nhập WTO","Trở thành cường quốc kinh tế"], answer:0 },
  { id:"b9-16", topic:"bai9", q:"Nguyên nhân chính dẫn đến khủng hoảng kinh tế - xã hội Việt Nam cuối những năm 1970 - đầu 1980 là gì?", options:["Cơ chế bao cấp, bị bao vây cấm vận, chiến tranh biên giới","Thiếu tài nguyên","Không có nhân lực","Không có viện trợ"], answer:0 },
  { id:"b9-17", topic:"bai9", q:"Sau 1975, Việt Nam đã làm gì để khắc phục hậu quả chiến tranh?", options:["Khôi phục kinh tế, ổn định đời sống nhân dân","Chạy đua vũ trang","Mở rộng lãnh thổ","Đóng cửa với thế giới"], answer:0 },
  { id:"b9-18", topic:"bai9", q:"Việt Nam bắt đầu thực hiện công cuộc Đổi mới vào năm nào?", options:["1975","1980","1986","1991"], answer:2 },
  { id:"b9-19", topic:"bai9", q:"Ý nghĩa lớn nhất của việc thống nhất đất nước năm 1976 là gì?", options:["Tạo điều kiện xây dựng đất nước hòa bình, thống nhất, đi lên CNXH","Chấm dứt Chiến tranh lạnh","Gia nhập ASEAN","Trở thành cường quốc"], answer:0 },
  { id:"b9-20", topic:"bai9", q:"Bài học lớn nhất từ giai đoạn 1975–1986 là gì?", options:["Phải đổi mới tư duy kinh tế, mở cửa hội nhập","Chỉ dựa vào viện trợ","Chỉ dựa vào bao cấp","Đóng cửa kinh tế"], answer:0 },

  /* ============ BÀI 10: ĐỔI MỚI TỪ 1986 (20 câu) ============ */
  { id:"b10-01", topic:"bai10", q:"Đại hội Đảng nào đã khởi xướng công cuộc Đổi mới đất nước?", options:["Đại hội IV (1976)","Đại hội V (1982)","Đại hội VI (1986)","Đại hội VII (1991)"], answer:2 },
  { id:"b10-02", topic:"bai10", q:"Công cuộc Đổi mới ở Việt Nam được khởi xướng từ năm nào?", options:["1975","1980","1986","1991"], answer:2 },
  { id:"b10-03", topic:"bai10", q:"Đại hội VI (1986) đã xác định trọng tâm của công cuộc Đổi mới là gì?", options:["Đổi mới kinh tế","Đổi mới chính trị","Đổi mới văn hóa","Đổi mới quân sự"], answer:0 },
  { id:"b10-04", topic:"bai10", q:"Đường lối Đổi mới của Đảng ta được thực hiện theo cơ chế nào?", options:["Kinh tế thị trường định hướng xã hội chủ nghĩa","Kinh tế bao cấp","Kinh tế tự cung tự cấp","Kinh tế tư bản chủ nghĩa thuần túy"], answer:0 },
  { id:"b10-05", topic:"bai10", q:"Thành tựu nổi bật của công cuộc Đổi mới từ 1986 đến nay là gì?", options:["Đưa Việt Nam thoát khỏi khủng hoảng kinh tế - xã hội, trở thành nước đang phát triển","Trở thành nước phát triển nhất châu Á","Gia nhập NATO","Trở thành cường quốc quân sự"], answer:0 },
  { id:"b10-06", topic:"bai10", q:"Việt Nam chính thức trở thành thành viên của WTO vào năm nào?", options:["1995","2000","2007","2010"], answer:2 },
  { id:"b10-07", topic:"bai10", q:"Đại hội VII (1991) đã thông qua Cương lĩnh xây dựng đất nước trong thời kỳ quá độ lên CNXH, khẳng định điều gì?", options:["Đổi mới là sự nghiệp của toàn Đảng, toàn dân","Đóng cửa kinh tế","Quay lại bao cấp","Chỉ phát triển nông nghiệp"], answer:0 },
  { id:"b10-08", topic:"bai10", q:"Trong công cuộc Đổi mới, Việt Nam chủ trương phát triển nền kinh tế nào?", options:["Kinh tế nhiều thành phần, vận hành theo cơ chế thị trường có sự quản lý của Nhà nước","Kinh tế một thành phần","Kinh tế bao cấp","Kinh tế tự cung tự cấp"], answer:0 },
  { id:"b10-09", topic:"bai10", q:"Công cuộc Đổi mới đã đưa Việt Nam đạt được thành tựu gì về ngoại giao?", options:["Bình thường hóa quan hệ với nhiều nước, gia nhập ASEAN, WTO","Gia nhập NATO","Trở thành đồng minh của Mỹ","Đóng cửa với thế giới"], answer:0 },
  { id:"b10-10", topic:"bai10", q:"Năm 1995, Việt Nam đạt được sự kiện ngoại giao quan trọng nào?", options:["Gia nhập ASEAN và bình thường hóa quan hệ với Mỹ","Gia nhập WTO","Gia nhập EU","Gia nhập NATO"], answer:0 },
  { id:"b10-11", topic:"bai10", q:"Năm 2007, Việt Nam đạt được sự kiện ngoại giao quan trọng nào?", options:["Gia nhập WTO","Gia nhập ASEAN","Bình thường hóa quan hệ với Mỹ","Gia nhập EU"], answer:0 },
  { id:"b10-12", topic:"bai10", q:"Đại hội Đảng nào xác định mục tiêu “Dân giàu, nước mạnh, xã hội công bằng, dân chủ, văn minh”?", options:["Đại hội VII (1991)","Đại hội VI (1986)","Đại hội VIII (1996)","Đại hội IX (2001)"], answer:0 },
  { id:"b10-13", topic:"bai10", q:"Thành tựu lớn nhất về kinh tế của Việt Nam sau Đổi mới là gì?", options:["Tăng trưởng kinh tế cao liên tục, đời sống nhân dân được nâng cao","Trở thành nước giàu nhất châu Á","Không còn hộ nghèo","Trở thành cường quốc công nghiệp"], answer:0 },
  { id:"b10-14", topic:"bai10", q:"Một trong những hạn chế của công cuộc Đổi mới là gì?", options:["Kinh tế phát triển chưa bền vững, ô nhiễm môi trường, chênh lệch giàu nghèo","Không có hạn chế nào","Kinh tế suy giảm liên tục","Dân số giảm mạnh"], answer:0 },
  { id:"b10-15", topic:"bai10", q:"Công cuộc Đổi mới ở Việt Nam được thực hiện trên lĩnh vực nào?", options:["Toàn diện: kinh tế, chính trị, văn hóa, xã hội, quốc phòng, an ninh, đối ngoại","Chỉ kinh tế","Chỉ chính trị","Chỉ văn hóa"], answer:0 },
  { id:"b10-16", topic:"bai10", q:"Đại hội Đảng nào được gọi là “Đại hội Đổi mới”?", options:["Đại hội VI (1986)","Đại hội IV (1976)","Đại hội V (1982)","Đại hội VII (1991)"], answer:0 },
  { id:"b10-17", topic:"bai10", q:"Bài học lớn nhất từ công cuộc Đổi mới là gì?", options:["Đổi mới phải toàn diện, đồng bộ, lấy dân làm gốc, giữ vững độc lập tự chủ","Chỉ đổi mới kinh tế","Chỉ đổi mới chính trị","Đóng cửa với thế giới"], answer:0 },
  { id:"b10-18", topic:"bai10", q:"Việt Nam đặt mục tiêu trở thành nước công nghiệp theo hướng hiện đại vào năm nào?", options:["2020","2030","2045","2050"], answer:0 },
  { id:"b10-19", topic:"bai10", q:"Đâu KHÔNG phải là thành tựu của công cuộc Đổi mới?", options:["Đưa Việt Nam trở thành cường quốc quân sự số 1 thế giới","Kinh tế tăng trưởng, đời sống nâng cao","Hội nhập quốc tế sâu rộng","Giữ vững ổn định chính trị - xã hội"], answer:0 },
  { id:"b10-20", topic:"bai10", q:"Ý nghĩa quốc tế của công cuộc Đổi mới ở Việt Nam là gì?", options:["Cổ vũ các nước đang phát triển, góp phần vào hòa bình, hợp tác khu vực và thế giới","Chấm dứt Chiến tranh lạnh","Làm sụp đổ CNXH trên thế giới","Không có ý nghĩa quốc tế"], answer:0 },

  /* ============ BÀI 11: VIỆT NAM HỘI NHẬP QUỐC TẾ (20 câu) ============ */
  { id:"b11-01", topic:"bai11", q:"Việt Nam gia nhập ASEAN vào năm nào?", options:["1995","1997","1999","2000"], answer:0 },
  { id:"b11-02", topic:"bai11", q:"Việt Nam bình thường hóa quan hệ với Mỹ vào năm nào?", options:["1990","1995","2000","2007"], answer:1 },
  { id:"b11-03", topic:"bai11", q:"Việt Nam gia nhập WTO vào năm nào?", options:["1995","2000","2007","2010"], answer:2 },
  { id:"b11-04", topic:"bai11", q:"Việt Nam đảm nhận vai trò Ủy viên không thường trực Hội đồng Bảo an Liên hợp quốc nhiệm kỳ nào?", options:["2008–2009 và 2020–2021","1995–1996 và 2005–2006","1977–1978 và 1987–1988","2015–2016 và 2018–2019"], answer:0 },
  { id:"b11-05", topic:"bai11", q:"Việt Nam là thành viên của tổ chức nào sau đây?", options:["ASEAN, WTO, Liên hợp quốc","NATO","EU","OPEC"], answer:0 },
  { id:"b11-06", topic:"bai11", q:"Việt Nam đảm nhận vai trò Chủ tịch ASEAN vào những năm nào?", options:["2010 và 2020","1995 và 2000","2005 và 2015","2015 và 2025"], answer:0 },
  { id:"b11-07", topic:"bai11", q:"Việt Nam tham gia lực lượng gìn giữ hòa bình Liên hợp quốc từ năm nào?", options:["2014","2000","1995","2020"], answer:0 },
  { id:"b11-08", topic:"bai11", q:"Việt Nam ký Hiệp định Đối tác Toàn diện và Tiến bộ xuyên Thái Bình Dương (CPTPP) vào năm nào?", options:["2015","2018","2020","2022"], answer:1 },
  { id:"b11-09", topic:"bai11", q:"Việt Nam ký Hiệp định Thương mại tự do với EU (EVFTA) vào năm nào?", options:["2019","2020","2018","2021"], answer:1 },
  { id:"b11-10", topic:"bai11", q:"Việt Nam là thành viên sáng lập của tổ chức nào ở khu vực?", options:["ASEAN","APEC","WTO","G20"], answer:0 },
  { id:"b11-11", topic:"bai11", q:"Hiện nay Việt Nam có quan hệ ngoại giao với bao nhiêu quốc gia?", options:["Hơn 180","50","100","200"], answer:0 },
  { id:"b11-12", topic:"bai11", q:"Việt Nam có quan hệ đối tác chiến lược toàn diện với những nước nào?", options:["Trung Quốc, Nga, Ấn Độ, Hàn Quốc, Mỹ...","Chỉ với Trung Quốc","Chỉ với Nga","Chỉ với Mỹ"], answer:0 },
  { id:"b11-13", topic:"bai11", q:"Việt Nam chủ trương hội nhập quốc tế dựa trên nguyên tắc nào?", options:["Độc lập, tự chủ, đa phương hóa, đa dạng hóa","Dựa vào một cường quốc","Đóng cửa kinh tế","Chạy đua vũ trang"], answer:0 },
  { id:"b11-14", topic:"bai11", q:"Việt Nam đã ký kết Hiệp định Đối tác Kinh tế Toàn diện Khu vực (RCEP) vào năm nào?", options:["2020","2018","2021","2022"], answer:0 },
  { id:"b11-15", topic:"bai11", q:"Việt Nam đóng góp gì cho hòa bình khu vực và thế giới?", options:["Tham gia lực lượng gìn giữ hòa bình, thúc đẩy đối thoại, hợp tác","Chạy đua vũ trang","Can thiệp vào nội bộ các nước","Xâm lược các nước láng giềng"], answer:0 },
  { id:"b11-16", topic:"bai11", q:"Việt Nam tổ chức thành công Hội nghị APEC vào năm nào?", options:["2017","2010","2015","2020"], answer:0 },
  { id:"b11-17", topic:"bai11", q:"Việt Nam tổ chức thành công Hội nghị thượng đỉnh Mỹ - Triều Tiên lần thứ hai vào năm nào?", options:["2019","2017","2020","2021"], answer:0 },
  { id:"b11-18", topic:"bai11", q:"Hội nhập quốc tế đã mang lại cho Việt Nam những lợi ích gì?", options:["Thu hút đầu tư, mở rộng thị trường, tiếp thu khoa học công nghệ","Chỉ mở rộng thị trường","Chỉ thu hút đầu tư","Không có lợi ích gì"], answer:0 },
  { id:"b11-19", topic:"bai11", q:"Thách thức lớn nhất của Việt Nam trong hội nhập quốc tế là gì?", options:["Cạnh tranh gay gắt, nguy cơ bị tụt hậu, ảnh hưởng văn hóa, an ninh phi truyền thống","Không có thách thức","Chỉ là cơ hội","Chỉ là khó khăn kinh tế"], answer:0 },
  { id:"b11-20", topic:"bai11", q:"Bài học lớn nhất từ hội nhập quốc tế của Việt Nam là gì?", options:["Giữ vững độc lập tự chủ, phát huy nội lực, đa phương hóa, đa dạng hóa","Dựa vào một cường quốc","Đóng cửa kinh tế","Chạy đua vũ trang"], answer:0 },

  /* ============ BÀI 12: LỊCH SỬ ĐỊA PHƯƠNG (20 câu) ============ */
  { id:"b12-01", topic:"bai12", q:"Lịch sử địa phương là gì?", options:["Lịch sử của một vùng, địa phương cụ thể","Lịch sử thế giới","Lịch sử quốc gia","Lịch sử khu vực"], answer:0 },
  { id:"b12-02", topic:"bai12", q:"Việc học lịch sử địa phương có ý nghĩa gì?", options:["Hiểu rõ truyền thống quê hương, bồi dưỡng lòng yêu nước","Chỉ để thi cử","Không có ý nghĩa gì","Chỉ dành cho người lớn"], answer:0 },
  { id:"b12-03", topic:"bai12", q:"Nguồn tư liệu nào thường được sử dụng để nghiên cứu lịch sử địa phương?", options:["Di tích, hiện vật, tài liệu lưu trữ, truyền thuyết","Chỉ sách giáo khoa","Chỉ phim ảnh","Chỉ lời kể dân gian"], answer:0 },
  { id:"b12-04", topic:"bai12", q:"Di tích lịch sử - văn hóa được xếp hạng gồm những loại nào?", options:["Di tích lịch sử, kiến trúc nghệ thuật, khảo cổ, danh lam thắng cảnh","Chỉ di tích lịch sử","Chỉ kiến trúc nghệ thuật","Chỉ danh lam thắng cảnh"], answer:0 },
  { id:"b12-05", topic:"bai12", q:"Việc bảo tồn di tích lịch sử - văn hóa có ý nghĩa gì?", options:["Giữ gìn bản sắc văn hóa dân tộc, giáo dục truyền thống cho thế hệ sau","Chỉ để thu hút du lịch","Chỉ để trưng bày","Không có ý nghĩa"], answer:0 },
  { id:"b12-06", topic:"bai12", q:"Ở Việt Nam, di tích lịch sử - văn hóa được xếp hạng theo cấp nào?", options:["Cấp tỉnh, cấp quốc gia, cấp quốc gia đặc biệt","Chỉ cấp quốc gia","Chỉ cấp tỉnh","Chỉ cấp quốc tế"], answer:0 },
  { id:"b12-07", topic:"bai12", q:"Di sản văn hóa thế giới tại Việt Nam được UNESCO công nhận gồm những loại nào?", options:["Di sản văn hóa vật thể, phi vật thể, di sản thiên nhiên","Chỉ vật thể","Chỉ phi vật thể","Chỉ thiên nhiên"], answer:0 },
  { id:"b12-08", topic:"bai12", q:"Cố đô Huế được UNESCO công nhận là Di sản văn hóa thế giới vào năm nào?", options:["1993","1999","2003","2008"], answer:0 },
  { id:"b12-09", topic:"bai12", q:"Vịnh Hạ Long được UNESCO công nhận là Di sản thiên nhiên thế giới vào năm nào?", options:["1994","1999","2003","2008"], answer:0 },
  { id:"b12-10", topic:"bai12", q:"Thánh địa Mỹ Sơn được UNESCO công nhận là Di sản văn hóa thế giới vào năm nào?", options:["1999","1993","2003","2008"], answer:0 },
  { id:"b12-11", topic:"bai12", q:"Phố cổ Hội An được UNESCO công nhận là Di sản văn hóa thế giới vào năm nào?", options:["1999","1993","2003","2008"], answer:0 },
  { id:"b12-12", topic:"bai12", q:"Nhã nhạc cung đình Huế được UNESCO công nhận là Di sản phi vật thể đại diện của nhân loại vào năm nào?", options:["2003","2005","2008","2009"], answer:0 },
  { id:"b12-13", topic:"bai12", q:"Không gian văn hóa cồng chiêng Tây Nguyên được UNESCO công nhận vào năm nào?", options:["2005","2003","2008","2009"], answer:0 },
  { id:"b12-14", topic:"bai12", q:"Dân ca Quan họ Bắc Ninh được UNESCO công nhận là Di sản phi vật thể đại diện của nhân loại vào năm nào?", options:["2009","2005","2008","2010"], answer:0 },
  { id:"b12-15", topic:"bai12", q:"Hát Xoan Phú Thọ được UNESCO công nhận là Di sản phi vật thể đại diện của nhân loại vào năm nào?", options:["2011","2013","2015","2017"], answer:0 },
  { id:"b12-16", topic:"bai12", q:"Đờn ca tài tử Nam Bộ được UNESCO công nhận là Di sản phi vật thể đại diện của nhân loại vào năm nào?", options:["2013","2011","2015","2017"], answer:0 },
  { id:"b12-17", topic:"bai12", q:"Việc học lịch sử địa phương giúp học sinh phát triển năng lực gì?", options:["Tìm hiểu, nghiên cứu, vận dụng kiến thức vào thực tiễn","Chỉ ghi nhớ","Chỉ thi cử","Không phát triển năng lực gì"], answer:0 },
  { id:"b12-18", topic:"bai12", q:"Phương pháp học tập lịch sử địa phương hiệu quả là gì?", options:["Kết hợp học qua sách, tham quan di tích, phỏng vấn nhân chứng","Chỉ đọc sách","Chỉ xem phim","Chỉ nghe giảng"], answer:0 },
  { id:"b12-19", topic:"bai12", q:"Đâu là trách nhiệm của học sinh đối với di sản văn hóa địa phương?", options:["Giữ gìn, bảo vệ, tuyên truyền, quảng bá di sản","Chỉ tham quan","Chỉ học thuộc","Không có trách nhiệm"], answer:0 },
  { id:"b12-20", topic:"bai12", q:"Ý nghĩa lớn nhất của việc bảo tồn và phát huy di sản văn hóa địa phương là gì?", options:["Giữ gìn bản sắc văn hóa dân tộc, phát triển kinh tế - xã hội bền vững","Chỉ để thu hút du lịch","Chỉ để trưng bày","Không có ý nghĩa"], answer:0 },

];